apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      sourceRef:
        namespace: longhorn-system
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
