apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      sourceRef:
        namespace: metallb-system
  valuesFrom:
    - kind: ConfigMap
      name: metallb-values
