apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  releaseName: cert-manager

  chart:
    spec:
      chart: cert-manager
      version: '1.18.*'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager

  values:
    crds:
      enabled: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        namespace: monitoring
        labels: 
          release: kube-prometheus-stack
