apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: '0.*'
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
  releaseName: metallb
