apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kv-secrets
spec:
  provider:
    vault:
      server: "http://hashicorp-vault.hashicorp-vault.svc.cluster.local:8200"
      version: "v2"
