apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:HOhF4V92c6jg+lBSNu4=,iv:knfl3nXq+fj48e1dup0Wh/uN3Axi3TygI57bSKqdiW0=,tag:YqmApR8zxAAAx9BREwpnXQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TCtrRVE3ZVIwd29aekt3
            UU9jQ3JWb0hlUjZMUEwwUEVpVi9obG9LV2swClNHQ3ZlN3V6Y0FWeU9mZjFxZVFv
            RTc5RzZ6NjlrZno2WTVBVFh4MlkyYWsKLS0tIEprU1JEUHVnNXhTbTBobjQzU1R1
            VndSYVYxNHFJVjR4UnZOUUgxZnVVcG8K889uJDEmKjBI2QsUbqAKvQrbRlRF5ATR
            KcIJsqq1NmPDDoIKOhQt7fWgCaonzsJ6FCI0VuUvXwzC0oCOw1PfNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:04:25Z"
    mac: ENC[AES256_GCM,data:YYdd300nSRRiWoiLbav/Ic3Q1oxaIb3iyyMNdLraFW3bBfJsaus1dbRoV4P9Orkg6z40CWHMYVWNhfZ2AetnBJMp49HTWoRZJhozKe1ZsW0knNypZCQm3ARY7+LYkj9wyk7EqJxy2bQ15lUE+D/wCxAquUgY6LaylhOMpJBPW4k=,iv:SSwv+iOT4cbQlHUpagTI8XguTTKCwvcotVY/fvPhaeA=,tag:vi7QYUQsqrl/w6WqNtPvqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
