apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-db-vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-kv-secrets
    kind: ClusterSecretStore
  target:
    name: grafana-db-secret
    template:
      mergePolicy: Merge
      data:
        host: "homelab-pg-cluster-v0-rw.cnpg-system.svc.cluster.local"
        sslMode: "require" # disable or require
        type: "postgres"
        dbName: "grafana"
  data:
  - secretKey: dbPassword
    remoteRef:
      key: infra/database/postgres
      property: password

  - secretKey: dbUser
    remoteRef:
      key: infra/database/postgres
      property: username
