apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./metallb

  - ./hashicorp-vault
  - ./external-secrets

  - ./cert-manager
  - ./monitoring
  - ./istio
  - ./nginx-fabric-gateway
  - ./cloudnativepg

  - ./actions-runner-controller
  - ./pihole
