---
creation_rules:
  # Generic Kubernetes Secrets
  - path_regex: .*\.secret(\.sops)?\.yaml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age: ["age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7"]
# For Implementing regex path on below:
# test1:
#   data: this need to be encrypted.
#
# encrypted_regex: "^test1\.data$"
