apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/longhorn
  - ./gcs-hmac-creds.yaml

patches:
  - path: httproute.yaml
#  - path: backuptarget.yaml

namespace: longhorn-system
