apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-pg-cluster-v0
spec:
  instances: 3
  minSyncReplicas: 1
  maxSyncReplicas: 2
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ImageCatalog
    name: postgresql-system-bookworm
    major: 18
