apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
spec:
  interval: 5m
  timeout: 20m
  releaseName: dependency-track
  chart:
    spec:
      chart: dependency-track
      version: '0.34.*'
      sourceRef:
        kind: HelmRepository
        name: dependency-track
