apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: traefik
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: minimaldo-pg-cluster
    ports:
    - protocol: TCP
      port: 5432
  - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: signoz
    ports:
    - protocol: TCP
      port: 4317
