apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pg-cluster
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: minimaldo-pg-cluster
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
    ports:
    - protocol: TCP
      port: 5432
