apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-collector
spec:
  interval: 5m
  releaseName: otel-collector

  chart:
    spec:
      chart: opentelemetry-collector
      version: '0.129.0'
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: open-telemetry
  values:
    mode: deployment

    config:
      receivers:
        otlp:
          protocols:
            grpc: {}
            http: {}

      processors:
        batch: {}

      exporters:
        debug:
          verbosity: detailed
        otlp:
          endpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
          tls:
            insecure: true

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp]
          logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp]
