apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: homelab_tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    - hostname: "grafana.nishantlabs.cloud"
      service: http://traefik.traefik.svc.cluster.local:80
    - service: http_status:404
