apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    credentials.json: ENC[AES256_GCM,data:AKL42UgWwS33C/5Dz0M4mVpVoa0AlhZ+R7JpAbXXVItvPkyVrTtblnxqULkWSVmFByoXdnMyEsjYN6RfMdTE6mtQl8OidoHUcutsiw1PKedU3SrgFHhIABRxU2pzlKrR/dsjek9qtJD5gPmaWyNMSZ68WTDbGTwHUWjzUGXT/BY7jZhoM0Zyvj53Q101GHrPeEgYoo3t0u5NZpAhEYDGAHgYkydAB5UAP8kkO2Tti6bOYhjVxi0SaA6pscd/EkdSFg==,iv:AIvwIlv4235SlPNeGh4lROCj0XwA7fGos0AfetzmVks=,tag:s1UJva5tJg4o2fyP6HZ6Kg==,type:str]
sops:
    age:
        - recipient: age184uxhteulqapkl0ue4lpyyn5pxlpwteynxp2367vykclxxzvxyfs6a66ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZWJrZHZya1U4YU5LNVlK
            WTNWOHQ1UVptcytuLzN0Zk5YcU1vd0VKMEJnCjhqc3ZJUDBMWUxiZkxWZitIYjBa
            bUhTNFBUSnRDOUlMY3RSMEdiTGtCTEEKLS0tIG0wN1lvNUQrM0lZMk43Q1VCRThj
            a2Rvd1JQSmdQbEY3akRXM2xWamg5NWMKYiqycDmXxSX/Qsz/rWP+Ttv9fPC8BXF3
            UI6wpssh9sebUoFW4tWpbFHkyYGBtcCc14/c2HP8gAdEtDMmMpyUag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T13:17:47Z"
    mac: ENC[AES256_GCM,data:1FpQ+as8L85lcMV8n/TcJ6iLVXxPK0wwKm5/oz8MZflt9sRxTVFHvJWpM++n4ZSpjhZcbBU8Q89xreuQHDRHyP9eyG2VUnlrO+t/RAGDUXrKk/WBGs9etI8S5xAL0fqgGKnHXq+GQiMJ+Gm8lkS/ypTHtUJfR4/2OutdMRRpQ+4=,iv:hL3CCUo7B90M7f33xTsdoUKFHNQuP8jT/5F/folmscw=,tag:ukV3lYrKsJ/ZDkYu7EHAUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
