apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    credentials.json: ENC[AES256_GCM,data:wDmq6iBZqEdAmilkygyjcPpTzLgfg+iBoCViEvDwojGE5TVJYe5Is1kbjcyGX62LbFTTm8YqtsaGuK6H9XW4QmqKm8SrkdjT5urVUGuES/bbMUScmtxhgfdn7FPpHbxhks4ooynoAftvpUMYlbaSt4HwxaXPC9WNzdMqch7ITTJHS+qIFNvzCj0rMQGO4XHYN+EPZ1jKc6LVCIKeCkSpGrCFqtMS+oSG7pvu6VssiKbe2Q3narSQ+wiQoWRyxwP89Q==,iv:9P7jzbPSY0GoE3OFFiVBlh4AWqoaGpsHeBgEjoWBlPo=,tag:TcKPSrxgaBW8kJIQs4y6fg==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNS94UFg1OXpOUDlyY0hV
            czhJMGFEbWR1OENTbDUwM2pObjIzVmF6SVZvCnRBWlcyYmVtQWczQXRqbHM1S0Fm
            ZkhBbGtVdC96b0FiQWxTSCs2L2FIaG8KLS0tIEsvMXdLdlZUMUNDMCtLZ2dVYnRF
            alRkWVFxUndUdmRESmxRcXV6Qi9VV0UKD+aXiLURZ/6eGS1sgpkR898VKFchEQaM
            c/9stKy2cKT1wMpkBScSXsZ0TQ3LtosiYufvziNOLA7oXeppn5mKEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:43:29Z"
    mac: ENC[AES256_GCM,data:THuTtNk2KTKYfu+pmhDgn5p/JMgpes4U04vdMLUQ1wvTnAterg8NLZPtr4I/xysOLOsIDGzYNMXQBRWR2aQ0xciVy59ZXdOBamwYZaVqq4deUu6SiB7RCOFDDzCYAwSvAylzBMCq8M//E76M8WXsbsDZ8ddV/EG6+hK/nITvjz0=,iv:0oJl5fpH0Vhy8oQdESAVH+LCoclUaLLZL4D9E1iItCY=,tag:ijK7MZx36ai4jMMI5ExugA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
