apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    credentials.json: ENC[AES256_GCM,data:/Uua2ILLo4pdK9YCLKSaQATex/0oHkRUCMj+WecFtBvaU4HzANm0x3Vz+m8t+JT2iOCNPQXkylaEfQ23Eq3n+ieUw1ZQ4IZMS9E0sSIKNheLg/l42Q2lBjVMhwrgjWpdEaa3AOS6k5fsAux3MHJwPoTZJzwflXQphnpTP/unwuLZ8f+cqyK5DyAT3a/hvWR3yFGczloon3lkEjwAPWvmnmr1/Pcq8sOeS0B4Ve9/L+y75SVItoTuUTvJaD+L82KIQg==,iv:wpaNq6MCO51ncWkCXBiGqZE4Emg/8AopraYy8YAfA9w=,tag:blikABseqqE7qZHcFjT+dQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdWwwYVZ2WnlWRzcvRitU
            YnBiV1JtdUVlYzdidGJUMEJBdzhZUFJrTGh3CkZ6SHpqVHQrUGtWZ1BGd0dRVWJv
            aEZOcjdOenl0Y2VrMEZOeVltb3phRHcKLS0tIGN6Z1NPNjdDSjdPaGlqSStGczYy
            MnlrSmJ2Sno1bS9lazRNMVVhOEFBRDAKev0MaavoVH46YtAjSK8B13Qj5ZyJlmnN
            m+GAJEtyaG3TW2IJJNpV2fShHlSbtlguyDm/vOExHHmna/fkDoRLkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:22:48Z"
    mac: ENC[AES256_GCM,data:bQcd8aoiHf9hPvjgRa9d9j8crgiQphIp1HwDXJa5iVSM26MUpeb+nY1pIAsr3tHK5G/sq4TkcH7M/33UiGiDxVx1zIaZFPYlm3fZHppRHUn6ecycLUWCD0sCJtY1fmBCkUB6xYVK1/dX6crV5kOF5LsILr4KyYHnJruQmbCdCUY=,iv:Y7hP9UjVr8v2EEm/OYW16KqLjHuvIP8CdcPM++pFah0=,tag:69EodzmY3ZlrDEekZFbyCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
