apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    credentials.json: ENC[AES256_GCM,data:2uAeCCJBWcS6/pmtG6BeujJhxHq1O97Am0ujYj1LaLame81qaqUYGacB7/pxO1Zq2W0vYGU/rdkWOZzucVy3uSW3KmbKGcJoGAJmhTsfBRTTTnJbjgcnGGmuGhTsyLepADSKKBmNCWGzgQ9+res94IGiZf4/oVHh1nLC+uwQBR36abhQ68qUXBsPV5UAVn/FSmR2+oPY468UXwjS1tduXHqpVq9vT5B2fM3Zh94A/6LP4/RynJ5OoNS4EEWh+milsA==,iv:TYB8F1G5jDkcHX/H0rBKpEnHGOoRkQOT/XviK5qLebo=,tag:4qriK2Ko363678cNbZ9JGg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRnJ6NkVBMVgrVkRwUmdv
            LzRhU01FdGxRVUlUblJNV2FqdjNmelNuc3dNClFDQjVhUlM0dmRidHorUk1yWVdL
            TnJWSWc1M0FxY2RtcVl4MnZPR2JHaU0KLS0tIExkd0UyVW9jMmhTYlArUGY0QWZq
            WVRiZG90b3hZWVFuNjNYNVM4RXU2cnMKYbjgtyIxKyJYhVf9QZ3uQnUeT6eXSSk6
            vWrIpsTlV3h6b/3Vbw3Iv4+Vdv7yGIfzL7mqbgDoiLh7eTvrkLww5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:09:28Z"
    mac: ENC[AES256_GCM,data:yOyx2B7+P9Jt1DxwW45fXNy8g0mUWGVnJreSPCsHptrOBQ9g4Agbuf+wxGq2s/q4GbRMOQrL5gyvOSxafPwLurj5zZUar8urELEg88IYg9h9b+KwztK8K3pp/qAaZX2o4iVeN5AACdMx2o0Fd7YqVpzPMCJWsu7qbuq/shbnnrs=,iv:PfVTOBO3HyJk7qSitK/7sTmN/4yFFUmpNj2Nl2JhD2g=,tag:T379C3hYVPGENG6tiJjdug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
