apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Required Infra 'Storage and networking'
  - longhorn.yaml
  - metallb.yaml
  - nginx-fabric-gateway.yaml

  - external-secrets.yaml
  - metrics-server.yaml
  - cloudnativepg.yaml
  - hashicorp-vault.yaml
  - cert-manager.yaml

  - external-dns.yaml
  - monitoring.yaml

#  - prod.yaml

#  - arc-runners.yaml
#  - csi-secret-store.yaml
#  - dev.yaml
#  - eck-operator.yaml
#  - istio.yaml
#  - kserve.yaml
#  - kyverno.yaml
#  - opentelemetry.yaml
#  - pihole.yaml
#  - traefik.yaml
