apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - repositry.yaml
  - release.yaml
  - namespace.yaml


configMapGenerator:
  - name: metallb-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
