apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: '0.*'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      interval: 5m
  releaseName: metallb
  values:
    prometheus:
      rbacPrometheus: false
      serviceAccount: "kube-prometheus-stack-prometheus"
      namespace: "monitoring"
      podMonitor:
        enabled: false
      serviceMonitor:
        enabled: true
