apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 30m
  releaseName: metrics-server

  chart:
    spec:
      chart: metrics-server
      version: '3.12.*'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
      interval: 5m

  values:
    defaultArgs:
      - --cert-dir=/tmp
      - --secure-port=10250
      - --kubelet-preferred-address-types=InternalIP
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls
