apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-info-vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-info-vault
  data:
  - secretKey: pihole-password
    remoteRef:
      key: kv-secrets/infra/pihole
      property: password

  - secretKey: pihole-server
    remoteRef:
      key: kv-secrets/infra/pihole
      property: server

  - secretKey: pihole-api-version
    remoteRef:
      key: kv-secrets/infra/pihole
      property: api-version
