apiVersion: v1
kind: Secret
metadata:
    name: pihole-info
type: Opaque
stringData:
    pihole-password: ENC[AES256_GCM,data:iIIrg1DLhlX2zOwWVwc=,iv:9sW5cSmsMOA4OukftoNg74MMxfFHKKe8DF5yw7svqUI=,tag:PYCeKJWiZbNQBLvPX/em7w==,type:str]
    pihole-server: ENC[AES256_GCM,data:dqUP2Br/QyhuKnvafXgikEb44Ac=,iv:1hpVN/rbzHMHqYdOgMmtsACIuuPigqTr2HxO5Z1n5Dg=,tag:0rV84jyskO9lZWJWOXCFRA==,type:str]
    pihole-api-version: ENC[AES256_GCM,data:Pw==,iv:7SRqy8XwrCuf0xik3C1v4TSbuMLEv0s/CzFKo2tLrqI=,tag:fatI/2eh7RHo9h0e8srX8g==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VzZTVW1XWjdEM2pncHhx
            NHV5c0Era2lJYlJacFpwOExac3AxQ3NSVzNjClhTRXJiaC9oeHNQRW04dUVaOVU0
            Q1ptNWRmSVhUd0UyN2JwUUcyMkZvRUkKLS0tIDVkbmxXSFpVVlBmQnZyZmlqWnFq
            U2hDdndqLzE4SkdHMTZ3V1M0aWJUclkKm+aQPaHQDpkV5rF0vx4v17QKwFooy0Ij
            kYvWjC0sMMWq8oZbTWLr85AzDNQQZi6FtsrTqM2/FyzGURJAWCZbxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:QfAtITNnxRCSUJXXJBZhpCsJm08nGycdThMhIcDyx3MKS4kKSEy3Hj4L2z4CAdYxayDFjuLFp9wThMKrWzipntHexh8148bQKoAixOhyo6wR6tw7AjSFxUZL98vnfTF88wHG2pi1ZCsY5J6tNc26vjHVsdzXSfGKmarHIxZ5GqQ=,iv:YYypaH/tADlQP3JSfj9OgnOzl+91eX1PmQpOenwC6k4=,tag:7C9leX+EAcm6PidHrDPS7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
