apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimaldo-backend
spec:
  template:
    spec:
      imagePullSecrets:
      - name: thakurnishu-packages-read-secret
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z minimaldo-pg-cluster-rw 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done']
      containers:
      - name: backend
        image: ghcr.io/thakurnishu/minimaldo-backend:6a38a5c
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: dbname
