apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimaldo-backend
spec:
  template:
    spec:
      imagePullSecrets:
      - name: thakurnishu-packages-read-secret
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z minimaldo-pg-cluster-rw 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done']
      containers:
      - name: backend
        image: ghcr.io/thakurnishu/minimaldo-backend:main-cd47455-1752910237 # {"$imagepolicy": "flux-system:minimaldo-backend-image-policy"}
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: minimaldo-pg-cluster-app
              key: dbname
        - name: PORT
          value: "8080"
        - name: FRONTEND_URL
          value: "https://minimaldo.local.nishantlabs.cloud/"
        - name: APP_NAME
          value: "MinimalDo"
        - name: SIGNOZ_GPRC_ENDPOINT
          value: "signoz-otel-collector.signoz.svc.cluster.local:4317"
        - name: GIN_MODE
          value: release
        - name: ENABLE_CONSOLE_LOG
          value: "true"
        - name: LOG_LEVEL
          value: "debug" # debug, info, warn, error
