apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: minimaldo-backup
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: minimaldo-pg-cluster
