apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: minimaldo-pg-cluster
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  storage:
    size: 1Gi
