apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metrics-server/

namespace: metrics-server
configMapGenerator:
  - name: metrics-server-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml

patches:
  - path: release.yaml
