apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 5m
  timeout: 20m
  releaseName: n8n
  chart:
    spec:
      chart: n8n
      version: '1.0.10'
      sourceRef:
        kind: HelmRepository
        name: n8n
