apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:UkoByNIoM/ngJhZwIF5ZMQpI,iv:DuEYCtwPl3U+00gEBJUFKfuebPgJNrBmjdWZo5Huk0Q=,tag:ECmZkOrC4T3CHfl7AJNsKg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MGQ4cURoNzlobEc0TXcy
            Vlp3VVRHYU51cWF3aTZLZlhibGxQSjN0QTJRCnp2b0pYRWlIN0MzUjBPbUZwbWJl
            aWwrcFFJdEVEYXBqajZXLy9CcERIQW8KLS0tIGE1TEFJRDdjbkRMOHJQQ0xYRVRQ
            SnQwelI4R2xnRlBtUXMwQjVjS2lHa00KaT1bUpP9tNSzKdVAl/YfCYXVoKj+Mg/K
            f/5pYW2MzoLO7FfQ0ci3HWNVDXHm2+vwrd5AOnBEGxkVottOVZDotg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:51:31Z"
    mac: ENC[AES256_GCM,data:bFuPk8IThyEWtYoqbIg93gFszFxOizUFegtiaF/3gIWG0RGCWS1QmHz+mP7ifsvdIiSfXc+DQsfVta1akC+rVmuWH2Weoni2eWuLDiIqwfBtnUwH+CksceeMqVZbvxarWOBWVvoOR/m8ieFbWhOJyRaJfvKnWuMF6Ub5qSdi6GI=,iv:Mk9d5yCenbFskZDujIzdRDCHdLdJC+PYj4JTitfTvRM=,tag:6SY7W9WFmIPhWvvhjcQSJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
