apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:x2kNfoniVW+GAyFCNUXzNoEx,iv:EioHCFsnCZRnrQ18aIPsiN5TnzFki0MIb9+ch0eKlRg=,tag:iEF2V/qcPf2gqE+ZGS8SYw==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTDVaVmhqbVg2NzBlWEx0
            T3RkZnhQSEZoS3E1aWlwaU1oRmZBWVcrYVRVCm9CbzZQQ1VIdUhyQTBQMWFOM0Qy
            TWdrQUVmM2syVXdKSWZveDRUVW1aazgKLS0tIDBTWHRPK2x0SEl2aUhLOUtYM3NC
            Z3grbzJyWDZ2ejJjRWdmajVvM1h3cEkK1au1MOQ0eWR6erTxbg2ArVsGauc8mpl0
            rxKqaT7mNE6Cudcg7IJ7bMVX1Yw2GT13Mh8fGsnHsY+r+NbWhghK1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:ihr9pDVyNrBcogotNqi/x/Jryz/4L/HAo0jw3Rdj8Bxmqx05/sMkq4Vhn9RR2obf5SMH/vthS4tFju6kzf2HpBU/4JMUxpR129VzY1vZU8/0Yviwy9lXZG35s3/BEdij5Mm1OIR05L5GhbqjRgz0fCghgOWNObZi2eWWU7Kbfiw=,iv:LM4E13QO9kqNJkc3Pip1oDKPQXwQdTPWxlvfSW60XCg=,tag:ohs3TofddYrojfZ8H8VTHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
