apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:ikk8NXXwaJ5TK5xR0U8+7trB,iv:avFjuayjrb4wSxeCmntzYvZF+X403X7pDfwdRCQXNM4=,tag:UMHs+pWs6uFmn+lEEyBjLg==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtOEtad3BBSUJOYlZyK2tD
            MEUzSkRtdzk2Sy85bVZMN2ZZSGVxRTY0bm1RClVJaWxZenE2dEVPa2lGdk8zV1ht
            MEZtMC9ZemtXL1pRQmV4bXFGa0duVlkKLS0tIHVxb28xUWdtem5sNnhHQWxPV09p
            NGhaUUZMekVvNFpYeEtQalFWS0hpV1EKTR5iG++SY0forU3KWNoianxt/uFYPue5
            qRZT9C4BP4I9giS9eVv/Dse3tACb9EarTqCWAPLpgGPQr5OpRsFw+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T17:32:11Z"
    mac: ENC[AES256_GCM,data:qGDGGUfI4O3lToH5UtmpkFMEIkASB6XWCCeJ8Vn4HuRahu7Uxeik4UROba6av1IkxN28Wbn6tY85ClM5kbc9Y/xo76TQA85PulIGQcslPan9ayxd9ZGZnugbLccE+7eXnzpJgkKrl1GXD9BtFJ9zXkXtUdmiyXuHZCBpZWbhoyU=,iv:O5mIVhkHiZvD7ycNukcz9FsgGAkuZsu25pM8fTXuCp8=,tag:hdXsF6XYEXPK3PhFat6a1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
