apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:of9viE4eQGpGQKDvR+5wdbot,iv:z6Wb+4V/baK4oNMY+PWecO1F5jucN6Bo40lDtTwxw2M=,tag:thV9jn+imtmbJfX3Q10Piw==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3djR5TzNBNmkvdzRUcmM0
            UnZlMGloUXlYTGFGUG5oVlE1YnFrRkRXREY4Cm5IdktvWXdrUVVtLy9QcDNIZTBT
            THEwNmtmK2Y3Z3FFM2NuTGFpekFMVlkKLS0tIHc3aGVyTmRzQzVGcFhmMDdnVC9O
            RXVYdGloMVFzbE1jYTFTcGJMSlNEUHMK8i4Ike/Ofd9CPrxVzneKtm631O8WzfXp
            72yqET2zxKNSVAg4taKBImyB1VHYRrggewfwvkpnufuyGBiBsBxcsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:22:48Z"
    mac: ENC[AES256_GCM,data:odUV/QEmxQf9UUzX22OWmA6RIkaE3BH1XFiDI5tY3rRERyKYITVyw6l9ThAAevBmj6o2vTA3oBOEwooj48iEa9R/1VvffliSLE22mNW9xmg1IPHdwmeF/SJF92HlgEeJsukt/9GtRyGRCZWS3gQb5xCuTy+ovQj9dUxBm9KtTqI=,iv:coOrpMfI4F53VEpXmJ12O0vYX6wPU/CspJsrfo0r7zE=,tag:HDan2mSaSqbvDwsvythBRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
