apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:U51KXlTk9jIIAJVqeIFu8SaW,iv:GVjd/ewMOoDa9paDf8277bGlrkmiyXvaKvT2jAdxm9Y=,tag:A8U/eG5lu8kVhrt41B0xFA==,type:str]
sops:
    age:
        - recipient: age1csm4q7qm27z74t9e42ha30pvujcm3a3gzhnvmpr04wwwsqjxp9jqhsnreg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TnY5TXZtazNZMlBXTEpx
            TlNLOEpTVUpvcmI1Vzc4cFFueHNNbXIwUVFrCk5kSUkzUEVKOG9SdDFueldXK1Fk
            N0hkQXJ4R0l3VHYrQitHYUJQTFpZN2cKLS0tIG5ZM1pmYjB1SEZ3dDhkd3pRcTJQ
            cTNJTkRpWkJSeVNiTkRQdEt0SHJNUzgKzFRrKWU/mQaEjx+LHygTFcjrfydJjJcq
            YKeWUXA2QrS3hlkJCdNI+pgeP9LJOljfJwrhFar8J4sR12pXqrGtpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T12:13:28Z"
    mac: ENC[AES256_GCM,data:JypYuGBAwjm6uI3fiDWDIYeXWRMUnFdJRbYxR0mJ+KZYv0Tj9lq+EwoX95FEiUBndQsW2PJVZMWhPaysrKRAFDrVrTOkFbr77gio5qnORFe3NvPg0P3mCOXUVZ/9tmchbyrzcQ4bN3zi7KfFCM58ill2j/ERer9PfC1C62fK+Xo=,iv:vtKk5Jr6rO/fEtwOJdix3/ENnQHvpl+4vNAxhXnH1Gk=,tag:7vsbU8WIFfSHxJQNOx5q9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
