apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:0mW/H86jKp4Q/BP2jrTRp9oe,iv:Wes4SIYFP45CbHA9oaeBmdpQ/NMMoIHbDBBVDuOGJ3E=,tag:hKZ6GveU0aVL9rI/mHQbbw==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMWRmU1lINit0WGhHeURY
            NE1hSFVXZWdISzB0NnZ3Q2tpa3NXemZFaHpVCmFOVC91bnJuVHZCY0hHNHV0RmlJ
            R0I2c1YwOWNKRnMyZWhyZUNhMlNsVFkKLS0tIEV6Wm5qRERiMDFlTXd3S0VPemt4
            RmNXZVpHSmxveWI0R3NvWkM2MllJb3MKq4Y+juysyc7tjqlNlYcr4UZtDiOROVji
            r5GonpnxhXc7xdOzsGAfZYqZv9LzteUmHg1ogkS+qg3NnPasfXaM4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T14:48:58Z"
    mac: ENC[AES256_GCM,data:eeLzVIm/Walypu2JMCWgrop9RFFRtynW+actqUofcBpPVbtOQ+mIDtER9VWWuxDhbhtbhPm9nQIMsejiEOF5F1iBsU3CDMuYlbnfsPWwg04FVbEdMKjggyZbk0GM4k5feuD6Aa7PXJsl9n3R0q9N5vx9msu6p3wBfUPTPP2yyjc=,iv:BZGOqzM5nHp12qr1A0MpYl8IvgDaKXC7VBv+wwVWk2w=,tag:8uZn+10/K754EAOBandr0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
