apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:tL8NUL3ARk6klb3jXcH8ppCz,iv:ZyujLeS+LSiQ+q3g0v2kDeA7n1JPPl0/v1rDwDPhizU=,tag:TPE1P2lAWRsykX9N+J/Yyw==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITzVLai9nOStWYWszTTlq
            blJuUXN2dlljRnk3V2ZXbjBOWncvV2VTVGg0ClNueUxNbmRzcngvTXpQc2krcWZC
            ZHBua21WK3ZHWFNqSzA0T0ZHZTkwbmcKLS0tIGhCRzgrWW1PSUVVZEFkWVFWV0dH
            SHFoSklKdFQwODZidm9lbDZnaGRqUEkKqFHb7E5ifR1Xo2z1XBCoWpwvANz0QMUf
            AstMV0ihG88gFUxvR9gb4EFd1aubYy0dSCelRGlqU6oBsZ9SANYmxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T15:09:28Z"
    mac: ENC[AES256_GCM,data:LK6fizWBxh5bQFGNOvFcUyZ43xk+gTnNnRN+QceTvTxUfopoU3htECRsG6S1WGI0DSgWlSVjVOZ6/72wBIlt6M4VpNsieM0FMl3oVImu2UJhVwWlaQV7169ZcvzaIC/5KE6UDC5c6tPpPilpxuDXanKv6FUBfTiCbnuzUfyT3v0=,iv:bCKfrQzsYJ26A62TGGXdwN6nzl/hZ5e7Hry8u/wH4Yg=,tag:ONG+cjGHIh/J83B0YuDq9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
