apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:JF61EcAYfQhxnX7jrJOR5gqD,iv:o4fDj4rspVHOlOTc8eWwscKkwYEO6kKJ1EhNV2RSA/0=,tag:ka4vLK8LA5gZhIsQFOammg==,type:str]
sops:
    age:
        - recipient: age1zq0k3j4gmj3k0xn98vzeqwtlf0l5m28pg0ha56x8rg3zs2chv36s3jv6n6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NHdDc3hFQ3BnSDJuaEp2
            U1VmbSs3RHJqMFlkL3VVSmNtTGRQU2ZXU2trCngxRWE5ZXpoT1daNXVTZFRmSlha
            dUtvaFJRa0lUcmJPTGRibmlmZ2tBT0EKLS0tIGlkSWZxNHRMd2xkcy9UREJrUUxy
            NFgzUzZzc1hmWW5GQ3JadXZsNGM5dlkKhpBO7DPSMr2uyLb2qvX83qyUuq6RyIXq
            UsUhmvStBFvDBa4ZuYvuqwtpIFd9m+y4ATRn2voQBPibw85X/BuVXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-16T05:22:50Z"
    mac: ENC[AES256_GCM,data:bar9skBgJi0YsvFGllSmcVIeCLdHo9V6BWdpfIgk9yK2rOv0DJPdcHlJ/yHkc8ujjwUjmXbmzBQkga8srogLhz1THSfOjqFUyUynILJyLSxCx7C49alxBKpbB9CRr0iJVe5TkwiEgg1DpUh/ZJGWnjeZTKBNLfvszSPsYhn1v/U=,iv:8+oQG/1sPAQs6AUt88rMaVinzHx5g0udEF6T88ACrhE=,tag:O4IUeUbSbdJD/Q+Q+3A1uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
