apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:GCi6bKbDfcEDsz7lvdiDJ8Zy,iv:zYQYbcDMg8zlnMycJCxdlXoWvbzAAi4tqRcsPJd/a5w=,tag:k4jo36DNdzH69rLpVDMzMg==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpK2R2WjhQWXlVazR5d3ZF
            RVB6NzVPM1U5VmdWVk1QcVpSV3F1UkxVWkdvCm8xc05JNG9OSjd6RUJHcmRJV3hC
            VmxmVmhnZDN0TzJDM1FCMGxVQUkvNUUKLS0tIDNUaWw2UGFKMCtnOTBvRERvam5z
            RU1PbGliUFVGalZoeDVJUkNLSk9uRkkKaLWMx5Vms5HPegeNu8lGpxyL8JFjGo3M
            vtMg2q72krt094c9G8ZK468QqDh2+kKEmw76fajuYnNBZiy4Cwr20A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:53:04Z"
    mac: ENC[AES256_GCM,data:YRRyIH4JRCtAwnb6eMhLZTjRqpPtGCjaMp2PvQ2woio30EmiJguuk8KKd+GaycZxJifw4eQ3cEUiEgqUTgW7lwqgBmY4TKJnfj9VMJNBPs63DKzLlav8bhiYgA93mIaK760gfbblkV7Ptl/AwL/jwa91+PGObGGZR45BE+GwlTE=,iv:iYpS7QxvNdXTmfRMhYEFOzoZTWlWqzE1XxRSab2r+h4=,tag:E7PSmcnwhWaaijDgT/NCOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
