apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:pSSR4KlVUjMtlD69DW1xkagP,iv:HhH7wOR7lZJGAEfkb1SJq7gVWbY5iUbhwQk14+kF5/M=,tag:o7gBwbkP8yhtm6NBAdivLw==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aGhKUUYzTkpIVG5mMlFl
            THpPYUhJZmpheWE5c3BQZDU2ZXhTUU1vekVvCmJERXoyT2JEL0pCRzc5L1MxQTVj
            YlFKSUhYbDBDb0ZCODQyNSttRUNLUWsKLS0tIFN3enZXeFB3NHdWMWVjS1lVNXk5
            TWxUQ2h3MUV1SERySWU1WlJrYkFkZW8KHfhQg0P8Tng4lTkEu4JWkXdMNTMQxeDh
            MDrXeIhJSiqtdrfRAgA/yUXqED0x/vt4OXKIXt5dl/wTX/WCwcqaqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:11:10Z"
    mac: ENC[AES256_GCM,data:01lrn3CeNrEtl/kyqjF125Ay0ZoXsVe3v4o3DDldgC5JFQchnL82SButfBf0lzdMZPjRFUbiU9H3T0upWmIJPqNWOllknA1fJAWP+mqycQr6nC9rvMtMDvPMhFyjlS6sA7qjLLCn12wGw6hrs3EPmtnM/7k0skPrdk5OHrNot6E=,iv:9Nh7rz5CJF1cpBz1Qd/4F8Z1qH7HHOvQx+3uvBIhZvs=,tag:eqe+ZD0Y32W03WmsopMQWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
