apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:s1KpbtvnkUDA8MQyiw==,iv:k29eWN3iO+pjPz8GmYmNmB9uFJrt/Ta4qFI27SiTG5U=,tag:pVQ2aR/AhBgPQdeRfB4Qcw==,type:str]
    currentPassword: ENC[AES256_GCM,data:PYs4Nc4=,iv:kbceo139ZZTxFw7xxp+CQGP2IECpn1n+jS5UhIa+ADU=,tag:Fkp2tjdErlIs+2Xfp8oN5w==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YkJwS1prd1pCNXA0UE9x
            cEwvaVA0aUtET0RQL3JIZkU0OS84WVZGTlNnCkUvMVc3WjVaYXJxWVdWeGV1eGUr
            WEEza3pjdUNsNHJGcW5lSlArWWpQdDAKLS0tIEF5QzJhakJBVlJoNm04THVkZ3RX
            OFJOOCt4VEtvY2pVZHhWZVZ2OTJwNkEK1txThKaod6a9z+onSgEsD+p3QyYBGJSB
            gheY1ZnohGAO9A9pKon9rz7bTUmfNCOmeQGXDD4EG0EWr7ftKQdUUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T15:10:32Z"
    mac: ENC[AES256_GCM,data:5yX55M+YojRcI1OkPOm95kS9Q6Zt3eIv9fDbEkVsqi6QWohA8u9SwFVl1NpA+BAGS98U37nKlX77a8uymdsc3yHOSZEVuiM+vBgci84QwQTfYaVXgU/4k3+6KfeOs6YiQjW7hkbi/5cBCsQfPdGr007q0EXb+rmyXof5LRlSHS8=,iv:cCTGWHuzQFG8u75SKL8ef2z6dwGdA/ZUVpx8m7aIRrM=,tag:OljO1O9MNBpcNylqfP2b+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
