apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:sjHX463aMbxURCw+ow==,iv:lPP64yiGm8jA0XJnV6zvLsaDEJKu+u8VOhBhSZdF/pE=,tag:twuceagFPZF+8+zoVUwSIw==,type:str]
    currentPassword: ENC[AES256_GCM,data:MJB0lhk=,iv:po2umcWNm1PK3SExT4QQtWYAPwjOiVUU0QQnFoHdhRw=,tag:/lLrAPlDXu2Oh477nJi5FQ==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNk43aG92VEVFbnhEZkFU
            ODdzYVM0bjZnSkpMcis3WWpVZXVYZEVGcld3ClJzMGwvU1A4MW5PV3cwelp6NWNq
            WWdBdjFlV1BvZWZNRlRSK0dsbnFMd1EKLS0tIGlDZDhiMU5OZkplMFIvcXBtWjJq
            WjFNQmloY1loK245Z0pVaG1Ub2k3eWMKo67Pu/5vO05kl/VQ6Q0cFpyGIBaAE0Oy
            igPFBqVcNSqp1HmcaU2cnolqOdMo4N9ZcKnetnbpThG6xgYhc6HhHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:43:30Z"
    mac: ENC[AES256_GCM,data:pl51M7c+pr4wYxhdSMDPTTCIeMI50mNTY2izVJA3rL53AtgC+qRV6X4eosfYAksEmli9hpC9EP8QsVHXbuhrx00eHzDEsnjzzlyQIBnsQfigx1wb21uvmFbZ70it/hWNcmGxVrXy6f/feJIJlgD//1PteBn4cPNV/nJJdILaZVc=,iv:iUQRwN8DBvNbN4V51nNPv3z2r/KzuMv40xOMvtmVgHA=,tag:QHc0P8aU7HlkZGGri7UswQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
