apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Z+Id0/eUIpEY2jGRSQ==,iv:1iLJaGoFMM4uv6jztHVS+Ok6ciLSdsCNqupN7eVGnok=,tag:RZnU7oTA4/ID/eX5yH+hLQ==,type:str]
    currentPassword: ENC[AES256_GCM,data:9dnevvE=,iv:tKouJtjWzErrUYv5n/34zf2C7GlkknUHd34nezWpTTw=,tag:JOPnly7olVOsHuLP2F/OsQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHB0eU9uZWdBMk9RRzR5
            K0MyTGhBRWYvTzJRSHZrbGM5TjZ0bU9VaTBBClRrYUk4QWg1b09CL1ZWcHBObFBU
            M3ZGcXVuTnZLdEQzZ3lOL1QxL0NmRFkKLS0tIFNTdG44Z0ZRMTV3OVNYU0ZWUFhQ
            emlzOFhObUVJOGtFZTJ3SU1vOGJGbmcKNIoPOSDK0nYoqQ9RTiPOVvDppgY1Z5VL
            UgREoJTFekGcD8ZhqW24W3bfKZpXCmeHhMnPXy5tjD7FJncATz1/tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:11:10Z"
    mac: ENC[AES256_GCM,data:uhm4hyWC4SS0Fhwxs/FmigUsktCSdq8TffRB8cofkdSXi9Txv4yBvWLNEoXElXW/nXXsqr+9+TB2ML1MEZ3nIX8a+xL6aKBWbQghucsXaH4XF/eKQqNpvA6wxKtnCRw2NjXvCXF3n7RWkN71/aTTp/0xJyznsYLLUEySIZsboQk=,iv:IIIMCslEb6JkwAI4GD2ZC82QRjd+mHbL5AhWNuboWtQ=,tag:EQdVEY5fHF2Z9/7r2fI4cQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
