apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:68OEeqAdHo3R3sxNig==,iv:EnAvkZO9qt6S/NenIxdUwzFTSE1nEJ/2AOU+Aq8/F40=,tag:dcEgh4FTDpONfs1jjUwOJQ==,type:str]
    currentPassword: ENC[AES256_GCM,data:owFU7eA=,iv:94gGPFeacWk2CybVGMEk3+i1Sp4MdjENU6ZsW+rftew=,tag:pRzvZFrsz+A5caZonfNuEg==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRREtPVkRobEM4UkRLMkp4
            aW8rRVVsR2sraCtMYTg1RklqWTRSRWd0aGpvCjUwcnBZbnlaT2s2OXZpTVRVbERR
            SjdjdVYvYitZZFp1MjRnbFN0UWtHSEEKLS0tIGNTV3RtYWhhQ21NZStXV2w5L2Jh
            cE9wYWMzMzcxV3lCUkxQakFUb25CYXcKFRMq3XzsD9i1TdmmM4eeWy/Y2GGDRsEC
            Om3sk8vGkhMVs6mNm/EHX0MVNqfxr7nYtle5a5g68VeQxkmI43tniw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T20:07:23Z"
    mac: ENC[AES256_GCM,data:LNSRfxHxEeXsnyry4ZMbX6IB27HARq1eEeLZ1Z+SlS9tcBRWAP6cYVx+8BFg5QliEOVvAFscV4+IgBsWGCenqNtPSmA3U3WoIfZs8vLRSLEg0ESLkwdQjreBjBhSY5ZDCkTXkqm2ATNybFXNyy6t53ngxwfKeNkr6yRFdIih8yA=,iv:H/PS9KY1YAlGfsHUIonX2he7HlRjto11KY7rWvtkn8Q=,tag:jEnMUiASdEGdwIqn3HprzQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
