apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:BrId0Qr0SIip6Dyrcw==,iv:V+FIdHpR8Z79ZsrhIf5evI6LEjgpJeccFHrAe8tPPJk=,tag:yVeiExsoGsgQe1f2zoZXNw==,type:str]
    currentPassword: ENC[AES256_GCM,data:V0N+S34=,iv:aPQt2i6M20hX9xZedpxcS1YT4RPc/1bxagRZKV/T5ys=,tag:fcZqzj7t2MiRd3PD0aCq0A==,type:str]
sops:
    age:
        - recipient: age1zq0k3j4gmj3k0xn98vzeqwtlf0l5m28pg0ha56x8rg3zs2chv36s3jv6n6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTGNUU3lCcVduaC9IUzlm
            bFVkMEFIMmsxdkFxUkY4bkJidFFVYnB5M0ZJCnpMQjBoR2M5WjZkMEtWTGs3UEhK
            SmhJN0dvOTk2a3IwK3FrdlVPMFNzOWMKLS0tIERuTC95Z2JVQkxsdEZaUU9JQlpS
            dmdNTGJ5ZlZOWXZrT0VVZUJSZXRyejQKf2bI645zILiUsi7JsFFZODJb5MY5M93X
            sD6fjkw4xf6sSGorD0ZSd/ISs4LZtsJC+kw1RuNxjd3ZHfc6ciChCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-21T11:23:33Z"
    mac: ENC[AES256_GCM,data:f2v43Jz1tELF2ZqCX8Wt2UfRfSc26SS3Ip/CgB05nFdZjElh20fpcn6LjTn3wrEwk5IuANEO6ItAmlRlEfZhFQfM8sgdCybJ76rzRXt4oUbLFSRjiOYzeer+T0ezsTrE/vs+T5njwtQJIqQDsRb+vv/EfnVM8X9K9FFYKcu2qWo=,iv:lAMal5pPWORk7XAyMTbmTj4jqDeA5GbZHTReYtqPuNo=,tag:M6t++la/A8E+85Ig4YWybA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
