apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:sQ5k3ih89/wszW2JQQ==,iv:VYjIKaekuvUO1EteNlsu3WEe5Q0JnL/pO/jA4mGoy2A=,tag:1gc6TQT+W7lbdJYXBQDq0g==,type:str]
    currentPassword: ENC[AES256_GCM,data:PhYVwNc=,iv:NeeySUtWbdw997ZcbgfOJlyIV7211ukrGuFEpEKbyTI=,tag:+dOQaADz/qvpGrwLNb0MIA==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreDVjN201eFFLc2F0M3ZU
            aTdkODNSQUhmdWhweUZUa281eVE0TlU5YVNNCmdSS3dBZDM2NGQ4QjBvSjF3ZExL
            V3VHaElESnZqOFNpbzdBSFVBQVorcm8KLS0tIElTaDNFZ3JSa0dBRmgxRStwMUZz
            WnBLTzMrSEJvWjMreVR2TWVtTUx4bncKPf6UkAqiRvLuFZMz8EvXxx9Tfk2HN+9W
            4E+Zmk1yI+FNlH7L3sDr/ObiW7FW3guo8+f8NGWKVn2fNhb8Fd49cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:53:04Z"
    mac: ENC[AES256_GCM,data:iS5poVNBihHPG4q6uMwWXxoesTYmVmLQBa0lj+XEhESXnx0rsAwhFxG/MIxVjtMqrLrxGByExJds98+jy3Cpu3CpOe7Ti/SUuJ77Ghk65lilPOJueyx5P3D2Hpw1YajqZN/taXgVKzEMeh08LGdDcHk2WnrBuHd2lDT7KHKk9/o=,iv:pG3FFEdHZ+ZA/WjdVahYeQm1SFEeCXLHKd7u26hnc9g=,tag:ufWGL6KvSTvRse3ovA/dgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
