apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:A6dz0TerNAfFnUUwFQ==,iv:rVV4tF6QmjrCSKWy4IHUNH4VtOXrx9eq3WvD4Ku1AnY=,tag:nkhXm4OBBreCrykXAy+z+A==,type:str]
    currentPassword: ENC[AES256_GCM,data:tk8RjFo=,iv:CWTp2iiFKWqa826q/+TrPMmmbp8sbphx9xK47XR7s2Y=,tag:XURFGcwHTncKbech/QdWkg==,type:str]
sops:
    age:
        - recipient: age1khzu05szp0um38uvn50knwv8w2puy64a9f6f3f0mjtc2lzpmzgqs7m23pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeldKOGVycm1UcTRxMVZ4
            ZGtxcTYvTkt0RWN4QWhIS3B3MTBMVEIrT0dFClVIVUxPWFFXZnY1V0swVm9QTklm
            UER2K1Y0YlFqbjRCSkN4TlR3WjN0Um8KLS0tIEJtY0YyaU1YWGpwZWc5VC9USzdN
            MWVoWURhVEFybUdzOTFuOHRzZkhreWMKmfCvfWhuMQLxlbVJuzS1fGEKPfKL613n
            eSYFfbtZpPvysDZ+io+53dGsUM4MUbHsfymXMGL+7CAiuCSiSrrvQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T09:25:01Z"
    mac: ENC[AES256_GCM,data:8LJZWShk80hRwveLeAX6RTC16iZXTsAHq2myErRBQk3pWcjEgH26abCclreEj3GrVesLOOT0ogx9gFRd9sWNKNQdSbjaUjekz3pqhrHwORDbB2Tn4cIu5PDh0KKHlsMM7mddTAU9ATPLAm+iYGCu1/Xz1v9/cnHD1gEvsHtMbDA=,iv:TM7qG9I2Q+5f3xOsgg3hP4/kqynRgLvFs641+3ZGPp0=,tag:dCVCIv67wwIUoL2a8ovxig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
