apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:w2GNTNYcJt2wLgB2Kw==,iv:8jX4VMkrTnn/B2fv7+/R3ItM3mzc6yxuQtnXGzk1meg=,tag:HJj+1MOCT4OKqbx8xmzOVQ==,type:str]
    currentPassword: ENC[AES256_GCM,data:2J/3T5M=,iv:B9h/6//xlTwCSNTLzCGDms7MKNp5Oj1KapUjf6zO9U8=,tag:f0LqYED/T8C4XF0rTKYidQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bERHekprVk9DQ2xJck5s
            cDh2elB4dUNsWm9OR1FXYUhSVnNCbUZkV21JCjhpdjViZkozM1JwaG5FSXFIdy9s
            OC91QlUzSGdJaENONlV4NW5VS00xQ1UKLS0tIHppTlZTcStvREJQNjFBL3RYSGY4
            djI3VnBuUUZFeXVhYS95SVV5SVhmNEEKnHgOQc9LWNUN9pCmcUWgw8isBX6mUy0+
            XtnWLHPEBxwJxpVDNzpJU4s2YSTa3UwxmeG7/9WHjW2dmrFulmuXww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:FDP79GFL3dH0greMtSNhojo5V+bXiPg3xLxYcYg/YHZEviGzM1mYSkYTd9JFat89U6QhzaF8jCv84peKMKu/OdK1G5ftIPISVHt5h6opRYrOa4kmsGbQlBhd6pWNlv9LkgkDWtI/0PHorJqijkhjxtDuZWxeWn5aLV17WqPftbk=,iv:Qz9ozF9YZdvB6L7uSrynA81oIl91m/+GdDwlicb/jcM=,tag:EOXQg+3nGY8wdM+GcSs1rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
