apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:UwdJqF2uCOqhmPsayw==,iv:P+y7Zl9p3uI7OqMdHvqwNchk8WKIyBDFyUCm0d+/7so=,tag:dpHSTXzGyXgAbU2degFgGw==,type:str]
    currentPassword: ENC[AES256_GCM,data:MtPmbZo=,iv:Dybo1y1f3Nt7WwBb4DCz94VECkoDg71b0BwVCuy4Jk8=,tag:yQXgCPmu79RkT3UIF5QO4Q==,type:str]
sops:
    age:
        - recipient: age1gx3ap0wplmckkjaqk8rp0gren8zjt30fjd724ntqdsnmw8td04aq5hmf3k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQnNwOWl3Mmo4R0ZGWHU1
            c2d3SFIyamthcjFXU0lXSGFQME1CcjBzeGtVCkdRb0l3R0RaN3pDSVo5UC80czBw
            ODRoZEJGNHkwYUcwUm1MZ2JlL2FHMjgKLS0tIHpwUkVnVFBheG4rS1Y0cGt3Znpw
            WGV0OThubm5Gdjhnd0IrZlNkVEZnKzgKBq6KTzkWX75uWQDoQjgWU8dmMuXfRXdv
            sPy1WqV3HAzLJNtTDPzTKcG+2K5qZnE3Ta16GjcHDNvGHRq8Nw09iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T12:42:02Z"
    mac: ENC[AES256_GCM,data:z5piFpO+/AmA/rEkn4BEBjjGVgNnL8hJDP9arTsIE44znzYwHOmQchPwrCXSfR09Jq4TIJrmf3xzlIi2rKBKccbwx5nc7PJPoEvaLZO9NUGOEzefXSSOZveYi78LexRr+D9dUBEymx2q3meDax1EL36HSeLdyNYR3H2mUkBx/Ug=,iv:KPZmA7CB262GTHY0tXikhk4q3hHnpTA0Qs2loAQZSeY=,tag:nqFgF+Z0VAj+sdI/ErBcXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
