apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:OmISTqwTM1YtCDOCLA==,iv:sbml/useKwr4LebhX4bJTAkpyio04fk2rBePu2CtuEY=,tag:4rcYP/UQYV8uUaGJcP28rg==,type:str]
    currentPassword: ENC[AES256_GCM,data:uf/daTA=,iv:+S2oG4yNHqnb9833cycmBkiaqGCghSp295NO3QFhi3U=,tag:57IQgfUJ0Ohbv4argK8Oew==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbG14bVlUbWR1SjhaRzRp
            UGpRcDRlVkgxM0JDcy9tOXBNUzhmZittbVdzClF1MUloZXJ3Y3hyVlQwNVd5MXVy
            RnZCQlB6Mk93Tk5QVUVXYlFyTzlDd1kKLS0tIEs5NlcyOGg3b2kvUFZWbE5NN3Ny
            OHFsLzVURlNuenh4Qk1IMm1PWXAwK2MKJTaJHEjuiTUPZ/mhu/e9MdrISm1Bb50D
            lOd5itvvxhoW/CbYdbe+31JnFwBxinFRI6WYxVm7JtqB4ttw0cu/xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T09:08:21Z"
    mac: ENC[AES256_GCM,data:omw8T88xi3TchBcOpPP2M3nO8L0SDXMOqifc0QofHHuuM5gk+zUB/MT6Gu+vROegQqPCi5qmRO+p7+BRaq9VGZw2LUg2Hg0ZBbTdEWfotFHs4X16zU+ciGtlqCcFp1+Lg0jvK+GtDeS9E/7QcthLoWsvz1jwFhvdteDo03cICfE=,iv:pv+RtLwqWaoESuy/gXkTTkV6ow3fFZvX+dzhUS+GTa0=,tag:TE62pIOp8t2YZpMRwWSbXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
