apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:2qCZqg6qx3Xq6wlELr+1dOCy,iv:HY0KJmitVfdB778vbu/aJdjmxfXZ4VgEiKDKY48+UQo=,tag:NxVYFeJ+Nw9QEHjbCjLyVg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZ3FvSEJ4ZkNFbDI2ZkFW
            YndxUi94dWRvd2JCOUsyQm55WUFGVWtmRFRzCnNjRUtwVGYzc2dUWUUrZUJUdmdU
            S3VGMndhN21wRGxxZmpVR01vZjZXUTAKLS0tIHB0d0lyZ05xcE5BdkRjS1ZSS2ov
            OVNnMUJoU2duajJVdE12cFhNMVpVSXMKY00ZEn5kRNA1RqBiuJ/hoySIpgiYZRFk
            0S4CZd6n5zRBpOnA4kiHCf6DcuZRLStJPOOugb42KOBTHDTw6MznFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:3KtWz9unoaHzYbFpVkkb0A2nHpf6XJrUuDue6JrVprCxYaymd0P2g85u1Ri3v1zED/aOAPJfKR5mJrW+3eTqSvSLOwHtLl4wUfRGpff9d80SOPiVR12a/kk3xSkCsigP5eXwbfzKh9jz/oUUsCrVmbIa8wnP5wuLsjeInt3G27Q=,iv:AZH7rrqd4B+fdXif/npgK+3iM/WN5xKxYFs7XMUnS8k=,tag:3kwVVG5txB42jhARGMQ0/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
