apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:qYruRadSJaOeV9GyxVXgvi9i,iv:Qa5WPriIdP7dDtGgawftS6ptpmtrRpJ82wD8hgGSd+4=,tag:gPBhIwhHF9dI6zGq1pZjZg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbUpUYmdqSUN6dDV4UlFi
            M1YxZEpzdEovVXl6a2dmei9RTE5NUG9paDFNCjJOdC9rejl5c0hNTDRLYUgrT0NJ
            RzNzSTQzTTluTjRMd0pYZzlWMTl2dHcKLS0tIEpqYlhsOTM5aUV6R1ZkT2U2SUNX
            eit6ZGFTbHBiVnhuQ3NtU3JHVHEwYlkKvTBqc+cJo4FwpCXIhdbMY338l367AYQC
            HH/gsQJ26oxznt+yBcSuc7xvdz61LGWBndMcWdb+H6JihQXaY2yPtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:16:27Z"
    mac: ENC[AES256_GCM,data:VqfP9I7tYutkIm42a3g77XCfmqEkyPZeyOuwnn0XCLFXqWr9h1H6FMrQMc6otPtwPU2ST8OCmWD0+4lYGEgyJRXVvON9ctDVxqE9BaXSr7fu7tx39UFvctBCixwfKvf6KyOtGI3MvqBLQcshrdW7XGOz2Fj4V5AKalM9HmNiYqg=,iv:c2wa7uz8G93B+W/gaf94aLtyrGrNb96PFFGbiG8n/KM=,tag:tTww39d1NtEAJfbCWhHnsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
