apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:fyoLvDWnr5IJYmWGkrrUtWsK,iv:R3G+Xfj7Z8lkqMbB2i0WPSoqSPRPwAYVPKmaTmV6mLY=,tag:GIg7Ie+BVVC4r5NiepSf2w==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsU2grcG9jaFkySDNHVFk4
            YmFJQnNyMmVsS0Q5NzFCaDFWbUsvKzdXOVJrCjNOUTU1WmVYWXNMSno0cDdDRlhn
            eERGdjNtOFVza0Z1d0lLWW1QUlhnOGsKLS0tIDNhT1hGQmU3Snh1VlEwMjM0azdQ
            OEFmNUplNEhiSXJoUnozYVB4N3JYcUEKTF0zh4WwuB1fX/gj/dY3LeE5XlZEsAhd
            ZN+BzfqEFSFEu0kullBQlT6o7sHyyFkidbpt95709QR5olBNxDonrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:04:25Z"
    mac: ENC[AES256_GCM,data:5lbFcIgIuobGtYVm16IPxqX0TH6Bij+Qzls8HGelPW7VFN1CtZUOQf9FVWOpU1WxfueV2IRE2m230bv48GtXGOni+7kTcch4LnxnoNc/iG1+09leax0iWx9MnW7FsSoFwPISgxjW/nlOVgHpcqGjQqH325cQO3NU9uTjSBa2xj8=,iv:Sn5V7u6PE9IXjDB/v03iMhOYK1KQuRfsTMHousZV+H8=,tag:NCYlmEnOqE2RUw7Qb9t2SQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
