apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:SeJVDSxyKF2Qn27ouQ==,iv:m5mg5m3MLzOOp3fJTaQS/DIYKnwp7P6H1jcAwWzv4/s=,tag:B1WkKcbg8yQ6cJmFUGngFg==,type:str]
    currentPassword: ENC[AES256_GCM,data:5OazYsY=,iv:aeeUmQhQneHfbaxeMBS86SJ9rgpefMSVhGJMmCDUMYI=,tag:edZWH+Q43/ca5eWnSOs2LQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxanpONHgrQVZXR1g0VTND
            WlR3VVgwN2NrRWhTSGllRnF5bHRvVWRJeGg0CjdvUitQVkpyY0RZaDZQOS9DalU1
            TEcxcTRDNmRhcGNaZ1FhejRVOGJWNUUKLS0tIHdncitxTkEzbERCVXBTNk5yUzRq
            MkR4ZnkwZHRId2ZDdGRwWmh2bUhrcVEKKJo5baNt90BF+NgP0JHZ7dCW1AvayHW0
            WdmKcNdgfAdO1jMI/ao6AHKNLVazWdB7cVAzIN6Lw2aB8T18tI9SHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:04:25Z"
    mac: ENC[AES256_GCM,data:VkXy9sqwjQqVCNimrAEKhAniVCl8QNA7LHk/j+JuTDXoJ04uNYxDQONw+2WfYFZIuMPqfBsEQiUIEESEzkAWPR8Lkxcx+YD6b1NE+hE5VbJhk+3ifjHEbAyECGZVIdcfA5SnVSoiWhGjJNlEGU6E64HO/2omnQNDCXcSCBzhmoM=,iv:x/JcqDGtaZrVVtYtTvhoX7FFa/UfyXRDy5PTYqXw1/U=,tag:z0G++CLV6RtiifyGiRow4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
