apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:y5TU/ITFgiQVVdZMsg==,iv:HXsvHoXlSqM5yDvYiQSgFixoGsf0HRhEC2LvKFfRyz4=,tag:gYxRgudbHSleJgBcmvOXQA==,type:str]
    currentPassword: ENC[AES256_GCM,data:HylhOK0=,iv:+WgcbrAESUPx3zFnKdT/8i1/jLa6xSZXgF0vuCVi8c8=,tag:4xsG5DRja8M6ZY8aSd5G0w==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVFpabGNXbFVITjlzOXFu
            a29IRUdaREJKclBncUFSWDZGTnZRdkVkbEFRCmxXOUlValhZYVdhVk5vM2dHWWhI
            ZmpJbUQ0c28rb3dSa1JzaXV5WmhYaFEKLS0tIENSeGxNNEdBZWNLQTJxWGZsU2VG
            V3hkeFEyT2xrOUdlcVNkTWhIYUpyT00Kf1e+CUR/KWvbhxSQrQPRpo5/aQ4rP973
            bdFfzc1oPNu4fNyVPE0bPMgqyRfiHmRI2FutozST+W6DRDucmO3z7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:16:27Z"
    mac: ENC[AES256_GCM,data:gsPtDoxaWbkYK4/oRwYYk1PRxpNqZlqyaU/0lA+c58Ce3eY+aCs2rO2FJXGiUCHnm+quEwuK6GF8Z1nKUqUWMxZRcVwSAAPb/Rm+V5JKRva1xZqE1295eQz7Eq1tsV2wlMdT0We/pc0WfepKlnZV3sHddvLbV+SIKyW+Jlt3OOY=,iv:XkfTbos8cIkNvqwSc6M0D2/hSyNsRp9rEZkiQAQt9FQ=,tag:tas/baVJ3tONOVVWBPTpyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
