apiVersion: v1
kind: Secret
metadata:
    name: sonarqube-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:uIsVLFEUAm5nRkmqsQ==,iv:c2sPlH0+5U80lkIBV30wXm2Qvl5/8+nGZhnL1ZLkebk=,tag:Yrwxz2K9NWpFizUJmWtK+g==,type:str]
    currentPassword: ENC[AES256_GCM,data:tsSgJ4k=,iv:+ddyfYj6W99OzoNJLfV8lXYxHWIrG55u0rfSoxoxxDk=,tag:L3glJ9jp6DtxKAGAJc+lsw==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzNwZGRoRElqcW4xUkIy
            L2ROdVZ6eWQrV3k1S1JGdjJRTE9ENmRRZHljCnFRSkxiZXN4SlBMR0xzeWxNUk1r
            V0RuOGh0aHViTVlHSzZCSmJvemJLQXcKLS0tIHRjTkJJcU9RQ3I1V0Y4bFFkNzIv
            SUJLUktJRzFmTW5ZWjFMS3pRVmJCZVkKXFs1S0ekzfZmaNnS0iMXKp1LbuQ+uduu
            GEVedWxUcV6DVx/2ds8Ij1JKQO2nzNw65vos9HND0NF1Yz4nSIwOcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:G7k6pATZRHIfvRbVD7vyak1Hv40FHVWew/7Jri2zYtqMRTrZLlNEh3e0bt55H1qhpVEy8QiqX8rU5GUMJn0Rr2htUxhUhYy+dCPrIBt4ODB8eWZ2InieY5DqFsLD/oZ+XKdM+iyMID2lBS6CwCTrtNM+mOrCX6E3ZKBHp6u7TG8=,iv:+BvjGcB6YZ3FMzwxG76fphyERY/jpxBaLOpWROL9/As=,tag:HAp4illvNsA45clLquHOjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
