apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:W9WhWnlvklawzq/R0eBT8rEpNdVITHs5gPq3J3+hG6RGQfe6lzKpMwLakGOSB8Acnfn9BqwY+dCDKAvWLtMPbjuQOH32Q6MHjzA8QL+RJKA9ze5vtuxqhMQOoiwehZUNC4fU9jjAtt7v,iv:FBxBq14JStBMUJSYJ7fjYDAym2nGOFf12bCKXmhCcws=,tag:GY4mD7bttMb0QGWyHkoi/w==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQ0N5Z0RwMFlFTnc4cVBD
            RlJKT2ZTTjRSdk03dHpqNGZxYWV2VGI2eUJBClcxYVc4WkNLR2ovamZ3dHdIRGJX
            VHFKeWFUc0hLTkErWk5DZ3haQ2ZmSFkKLS0tIDZlZXdnd2NBVy9PWXg5VEpGa1JI
            L0NHVVpZT3ZSWVR0dmZWeDFtV3FONzgKqAeB5OR/MO6KQl37ONaXN2jycO8VAqpn
            cdiWLPOvpTF+4FrDPiD9pgD5Xx1GsU1efZMmDUszMLFZkq3JNM7AIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:xHhyIjLsb539hb1qGppWRkSIMRLXybJat26qMZQHoTJoS9sW6fHT/3M5etwm6GNpdKr+Uv6/BtKuncAc9ZCef2acFzANTZ6UCmWkFBkLZerDM0Qps/kipvjytOSwlKJ+zYY8wzx2tYyChDNVtGlvlLOj0v5DVe8imOoadNWm5Ys=,iv:3C/tKAMnoKzIMMjHtUnuFiPXfsGqGocBVb24FiuQYi0=,tag:e53ba8fupa5g0RMM8KBCIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
