apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:g8ddb7e/rJF/D1sNvXP/VnwMEI1L/ALCVx1L9NDGv7juO5SiNnTdwgbdWY/VOx8ABcLaVb+x35tquCij75YMa05RMgUUYCPREacYT/p0NEbOX79Dw7QY8AKLHcoZjea1rMIYyr9reXst,iv:ktSVtD5YmIXh98/NKHbzTaiLz5xb8Ht5zk3bJIpawTQ=,tag:5x/emLr2OkwLi0gWCkD8rg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTHRGemFLcXg3S3A2M1BV
            a1VCZXJTTHNIdmtjWkZHNkNEeTh5NEJrQVdFCmNJU3dYeHpETlVMUy9rVFBoNzF2
            VEFZdWdwa2Fta2w0SUF1RlVVL3RuNkEKLS0tIGR4QnpoV1h2R2NXaGloUUt3RGp5
            ZUpDUVlvelRORkhsQlBlNzdZOUVkYzgK/1i+P8W5HkJ6kpeks1GTiPNQ4a9yjNhA
            YTcQNXoKGTIGUvJ5ZMDByxo+P7ivo7Lpd/kPytWOyl6c11qneYPj8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:04:25Z"
    mac: ENC[AES256_GCM,data:W6rV777fN3EUVSmTh6Fgxv53lV+1/PrYZ2Z2BjSs3RQ/LHypLlsDhUQmIf1DtZtXe+wgJbdQbmegQg9qM+SpmveTHqBJT0FahLwh+hN1v6y859y2cOoFBrCZUZo0363WOY3TG0Jv7IGjCQZ8rMEh4bbTb8SzLQy6JUC0+gySYAU=,iv:2AgWhpQ6IsvZEfgHkbpyxTy4E3dqTzuUewZdjrPYbLM=,tag:TRiBRKyDMfTb4tHDIuBL6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
