apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:zIFZRo5f3QSWuSgV9IgXpHLqwDAorn8WZHKrn3ypkglgJM1BxgciSCNTwHbOKXnPUOC6ga5jmdJPDayViqV4zHk7Pi2YNFi1jbj7I0cxSPmDgiuszagzvNTAkroP8SH8KK+Sz1uBo1Kq,iv:cnxeR65XPiYXyMz+S9j/d4inmpIy765OQ5KavNOXFzs=,tag:K7t1DzS3ZlQEVapctMkdUQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bkMveXViZGxSeDFIdSs3
            bFJpM2FmWWNqSXlsMjNnU203MVRDbVNaRUFvCm1Mang1Z05yU3JXRFNIN1lXTVlT
            Z1k4SzFQYUxlUUxyaDExOWk2SGJEdTgKLS0tIEZvbjBWbUl3SnJFN3FmdDZqc1k0
            dzJsMjB2UElrYVQ4eGtXN0NvRk5kTWsK+awlsVCA/8e1OO95tqYP4UcTNs3A839s
            Nka7feannxHeKcJsuIzMpcKd7poicYJKkGAW6Ny50RjncunK/Nme+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:16:27Z"
    mac: ENC[AES256_GCM,data:5MuOUjSefqzaO17TTqaZzp8bZl0JV5W2SsTOu2NwnsN2ro0OV/1XZBQBW5YP8FjCZC1nGsKiMHrdBf2GeMzIifR7krWaLpLQsOP0SJKA3SEsg9l+flNUtXXjyYGl1AtI2jEMqh/NnE+cuunTPHlqoz9c2fMlngbbGW2yBAUn1S4=,iv:vQ6LIR4y5n7qMHf9ie4BEpdsK+76ZPce7W9XkUPSXQs=,tag:P7GhvNfeRjXFrU649tQspA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
