apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Z8NrQ497hFmgwMar2IMoJLg/RpIIW2eZGHO2pOZ9li7GBxob+Vdw+ArBlWB86tbxE+8C8HmIkOUZZ84ACjLvXPARqYTipzmhBBXa+IgJ9if7BWYlw+9a0sfdS5cUzIb1Qbb1icqCwNTw,iv:R+jVzRM6LmRqBGjCfW+DLtn6rtQH81e2SXuoJ2GY02o=,tag:2xNP3tQUEaxFnLOAPWbrrQ==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRWdMR3JFMTMybUh5dzVQ
            L1Q1bW9DYVlKanVHellUMEluRDFxbkZWUUE4CjY4eldVZ0FIMVdNd0N2WUZHNHpP
            NGZhL0VXS2oyb3l2QTc4dzJnUHgxMTgKLS0tIHZZR0tLMTdMd3E4VURsaWoxUTJM
            WGloZmhvZS9wNGQ4a2o0Q05HQ0tXeUUKlplQEnHY2zVhIccPug66aSwzpJFbSw/J
            WGyfZ6Wm0fllfPmQTx8mwfWOhdoSCo29oRzbcECtuARz9ACDl4kgeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T14:48:58Z"
    mac: ENC[AES256_GCM,data:o5eAGWvykmtNtvWyEfMtv20Kn3wa7ZLLxVbhzp0HuC2pfxzDezQT3jP0CTUJSaQ8FSFSFsv5ddTmPga4/mN9v32r59HgkfLjF9Cme4Xxl41pyaXlYiawBx1WuSEsFY8NcmFIkk4oJoUlru5h3bN7shz9/koKRyFeCSXESFJHnKE=,iv:e7OSvMGhKnbuoLRP0465rde6ZGqW077pzWatAoFi/RQ=,tag:WQD/Ip7OTL9+78BKX/X/ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
