apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 30m
  chart:
    spec:
      sourceRef:
        namespace: metallb-system
  valuesfrom:
    - kind: configmap
      name: metallb-values
