apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Required Infra 'Storage and networking'
  
  # kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
  - ../../base/longhorn
  - ../../base/metallb

  - ../../base/metrics-server
  - ../../base/external-secrets
  - ../../base/cert-manager

  - ../../base/nginx-fabric-gateway
  - ../../base/hashicorp-vault

  # Requires vault secrets.
  - ../../base/cloudnativepg
  - ./external-dns

  # Requires vault secrets and database configuration
  #- ./monitoring

  # Add other production-specific controllers here as needed
