apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Required Infra 'Storage and networking'
#  - ../../base/longhorn
#  - ../../base/metallb

#  - ../../base/metrics-server

#  - ../../base/nginx-fabric-gateway
#  - ../../base/cloudnativepg
#  - ../../base/hashicorp-vault
#  - ../../base/cert-manager



  # Add other production-specific controllers here as needed
