apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Required Infra 'Storage and networking'
  - ../../base/longhorn
  - ../../base/metallb
  - ../../base/nginx-fabric-gateway

  - ../../base/metrics-server

  # Add other production-specific controllers here as needed
