apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-values
data:
  values.yaml: |
    prometheus:
      service:
        type: NodePort
        nodePort: 32004
    grafana:
      service:
        type: NodePort
        nodePort: 32005
