apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb/

#configMapGenerator:
#  - name: metallb-values
#    files:
#      - values.yaml=values.yaml
#
#configurations:
#  - kustomizeconfig.yaml
#
#patches:
#  - path: release.yaml
