apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:fxjAX7V8CKFmBW38EYQ=,iv:cG/sHSKRgGP+z9DKX28KywofNPP3P1QusFhJeElvu4E=,tag:osPgIZt1uedSGr3fLdG0Jw==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc0Y2QzJKakx4bjA4WktL
            eGYrcjcwYUlqcUl5K1VTa0xLRGxjdWxXK1R3CkRtSlY1dUZ5WFo3ZnNUVXN6SjBh
            ZVhxY3JmNmVmcmtsa1J0cSs4MTlFODQKLS0tIFBhQW0xQmhvaWpTYitIaE5EdW53
            cFdsNFc1MlZGQ2xlRDZ5NDIzUXRnWEkKJQWNIIabPZgZT6boGdLBkXJTznFWFljP
            rZLpwtqK0RwPJvsnfYtU3Xx/+cWxuvC3G6hJ6xzPSpGazuC0Jv/dGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:16:27Z"
    mac: ENC[AES256_GCM,data:n5IqioloEz+QyVtLPvkiFtuiIm6DJN4EhOQAj2dZPYj9aR3RUiIBj5d4Ku4Od6JHyAd5e07qhGyjrk6BIQdM6WqzWnv8H6V5tyHHWsUo8iZ1JthWyNvO80t9bmswf+Z3VC6Xg7cUHVviEsZjtEuJjICtZxSK8kpN23zoS4ibzq0=,iv:qmmTMBmlJ40vgji9uBd+rjCottuAsFG50iWKT/YkbKw=,tag:+6UiBQ6Rv9Kx2olPboNelQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
