apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:CC/Ualw0DQ91lFMW67k=,iv:xBRYU0BgRNn/hwILfQggbIqFqbVlpDQqBOJbTFZJht4=,tag:DO2SAvn+ZAdq/qzsoz0DKw==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETzRqcUNmUWY3TXZTa3dC
            Z2dZMmh2aW5Fd3BZb1k2WHQ2RTBqRHhFRXdnCjdlZnJlMjhpSmRuNEhGTGpIa2lD
            TnRIbmlKUFFCbWpFcjhjbm5DYTF5c3cKLS0tIGdlTmFrTVN5WlMwMHkvcE52QjI0
            d3NUdS9WelNKRUR6NEYrcWVGWGpkUkUKONFb2pM3WtqYtDE0D2GiZzTe6MZ2D+TV
            1a7Nmdl+N41g8p0kkiT7kq3MxATqoDmyHCYVU2BKAIMRKQM5+3FUxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:ougXqwGQFEDI6I96VYCodKoTXaIHbn+LSAKix5BgkNyeRLfl/zYon9mNvgVwlsErUzor9kORVdkq1rrrO9nPFG4/VPQQA4+DEOrle6QITbQLtD0OtsQsoKf0RePyBgC6i+eVdxULRgSlMqJKz5oCCwcKbDOVd5xABFHy8nDTRns=,iv:ja897dM206qwWDrV/aXzpdOHin3Xd61bQ5opWlaJAz0=,tag:xJNBTB7O/5w3MLMlpxpqbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
