apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  releaseName: loki

  chart:
    spec:
      chart: loki
      version: '6.30.*'
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
      interval: 5m

  values:
    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
    write:
      replicas: 0
    read:
      replicas: 0
    backend:
      replicas: 0

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
      schemaConfig: 
        configs:
        - from: "2025-06-20" # Current Date
          object_store: filesystem
          schema: v13
          store: tsdb
          index:
            period: 24h
            prefix: loki_index_
      limits_config:
        retention_period: 48h
      compactor:
        working_directory: /var/loki/compactor
        compaction_interval: 5m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        delete_request_store: filesystem
