apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  dependsOn:
  - name: apps
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./policies/networkpolicy/development
  prune: true
