apiVersion: v1
kind: Secret
metadata:
    name: longhorn-gcp-backups
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:A1Wr2ZwL248P3w1qaaaMoLhfa8nV+bTwF3mKJAGRz7rP5/g7LblbAfcWRFgJEUPoWlvLv/WrlJPvWGbIpA==,iv:b0EZT5MctBikR9s5Tivh1jERS8i3ZfKB8bLV6qX289c=,tag:tGKz+YOaMID1xhfiM+uZCA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:IoVfFU13YmZs5CW2jd9hF0staJHoybldR/eiJzIR,iv:GbV56V/q2Hlx9DnYtKoTgvbdgoB7l1V6lR8N16E31nA=,tag:IDlWk/rGlaf8jPkUwSQiOQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9+6YbAHOpZz14jQLgEfUNXKWyAQEelYZN5dSN0QmmiYHOO0yU65ynw==,iv:/34BS8HGonzvObqPNlk+CL9ed7iG1rSNKpeg2CuyJl0=,tag:lcFiN842T4AlPfa6UV+5pg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWFFYNU5qckswc3l3SlBW
            cVNmVUZ4TnRCZTZjL0JxUmhZKzlUSEpydUJ3CmVuTnI4Z2FDMStmM2twNTBKV1My
            Mjl1NmNHSVd3K25hZTQ3a1drVUNpeDAKLS0tIExJZFMvNEkzeTZBUURRMmNaY1lq
            TzJCRkRWZlo5RXhqWUJwUlFJVmxaOEUKWOxBSLuyBn6415Osel9LGL8Ngtjl2jZ/
            MTxD7119S9SdQJEZGiGYxjemnD42CUl4MBLwd5yknJPsO5odPYgyCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:NF7lfRHu+VD//x/Ehzz0ESgF7+MmUhGhvOMVA7BWqx9hCYtGGf66V6NYeldFFSLv33PrUp0UnJxVZ1+Ek8WUhTcDEBS0+wQzvRhxtNBN65jGpSzmZ0RPsyHd9nNxpxtfX1HgfG1SQgRvQtF4TnR+B4/5npKSqkBxfenSa2LSWzo=,iv:IJqRTbtCC1tn51IuXVICGV1JSuAcjQS7QvOZIyLWyVM=,tag:eAByWAokmqVBEtodgm6clQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
