apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mlflow-pg-cluster-v0
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
#  imageCatalogRef:
#    apiGroup: postgresql.cnpg.io
#    kind: ClusterImageCatalog
#    name: postgresql
#    major: 17
  storage:
    size: 5Gi

#  bootstrap:
#    recovery:
#      source: clusterBackup
#  externalClusters:
#    - name: clusterBackup
#      barmanObjectStore:
#        destinationPath: "gs://homelab-backupz/cloudnativepg/mlflow"
#        serverName: mlflow-pg-cluster-v0
#        googleCredentials:
#          applicationCredentials:
#            name: backup-creds
#            key: gcsCredentials
  backup:
    barmanObjectStore:
      destinationPath: "gs://homelab-backupz/cloudnativepg/mlflow"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d
