apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlflow
spec:
  chart:
    spec:
      sourceRef:
        namespace: mlflow
#  values:
#    global:
#      storageClass: longhorn
#    clickhouse:
#      installCustomStorageClass: true
