apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlflow
spec:
  chart:
    spec:
      sourceRef:
        namespace: mlflow
  values:
    extraArgs:
      - --allowed-hosts "mlflow.nishantlabs.cloud"
      - --cors-allowed-origins "https://mlflow.nishantlabs.cloud"
#    global:
#      storageClass: longhorn
#    clickhouse:
#      installCustomStorageClass: true
