apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlflow
spec:
  chart:
    spec:
      sourceRef:
        namespace: mlflow
  values:
    log:
      enabled: false
      level: info
    extraArgs:
      allowedHosts: "mlflow.nishantlabs.cloud"
      uvicornOpts: "--log-level=info"
#      corsAllowedOrigins: "https://mlflow.nishantlabs.cloud"
#    global:
#      storageClass: longhorn
#    clickhouse:
#      installCustomStorageClass: true
