apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 30m
  releaseName: traefik

  chart:
    spec:
      chart: traefik
      version: '35.*'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 5m

  values:
    ingressClass:
      enabled: false
    gateway:
      enabled: true
      listeners:
        web:
          port: 8000
          hostname: ""
          protocol: HTTP
          namespacePolicy: All
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
