apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: '3.*'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: metrics-server
      interval: 5m
  releaseName: metrics-server
#  values:
#    defaultArgs:
#      - --cert-dir=/tmp
#      - --secure-port=10250
#      - --kubelet-preferred-address-types=InternalIP
#      - --kubelet-use-node-status-port
#      - --metric-resolution=15s
#      - --kubelet-insecure-tls
