apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  interval: 5m
  timeout: 20m
  releaseName: sonarqube
  chart:
    spec:
      chart: sonarqube
      version: '2025.3.*'
      sourceRef:
        kind: HelmRepository
        name: sonarqube
