apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  values:
    grafana:
      enabled: true
      admin:
        existingSecret: "grafana-user-secret"
        userKey: user
        passwordKey: password
      envValueFrom: 
        GF_DATABASE_TYPE:
          secretKeyRef:
            name: grafana-db-secret
            key: type
        GF_DATABASE_HOST:
          secretKeyRef:
            name: grafana-db-secret
            key: host
        GF_DATABASE_NAME:
          secretKeyRef:
            name: grafana-db-secret
            key: dbName
        GF_DATABASE_SSL_MODE:
          secretKeyRef:
            name: grafana-db-secret
            key: sslMode # disable or require
        GF_DATABASE_USER:
          secretKeyRef:
            name: grafana-db-secret
            key: dbUser
        GF_DATABASE_PASSWORD:
          secretKeyRef:
            name: grafana-db-secret
            key: dbPassword
#      grafana.ini:
#        smtp:
#          enabled: true
#          host: email-smtp.ap-south-1.amazonaws.com:587
#          from_address: "nishantsingh.work.503@gmail.com"
#          from_name: "Homelab Grafana"
#      smtp:
#        existingSecret: "grafana-smtp-secret"
#        userKey: "user"
#        passwordKey: "password"
