apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./metallb
#  - ./metrics-server

#  - ./hashicorp-vault
#  - ./external-secrets


#  - ./istio
#  - ./cert-manager
#  - ./monitoring
#  - ./external-dns
#  - ./cloudnativepg
#  - ./eck-operator
#  - ./kserve

#  - ./csi-secret-store

#  - ./traefik

#  - ./pihole
#  - ./actions-runner-controller

#  - ./cloudflared
#  - ./kyverno
#  - ./opentelemetry-collector
