apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 5m
  releaseName: cloudnative-pg

  chart:
    spec:
      chart: cloudnative-pg
      version: '0.24.*'
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system

  values:
    resources: 
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
