apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/fastapi-app
  - ./configmap.yaml
  - ./servicemonitor.yaml
namespace: prod
patches:
  - path: httproute.yaml
  - path: fastapi.yaml
