apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
data:
  values.yaml: |
    ingressClass:
      enabled: false
    gateway:
      enabled: true
      listeners:
        web:
          port: 8000
          hostname: ""
          protocol: HTTP
          namespacePolicy: All
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
