apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:isuMbN/uMRoYz8K8APyomioPJNgHsqegRzMwNrlxhHqD+ks+myouDtS5fpKMpb/5Pd5A2Wy/lXdBNHFJVHxf0DNOeVKCnNgG5oyl0lpyvmSRe9XNqUz5AnBcZcgs8e+q22dTvK01wmJ/,iv:gH6mzKJSKMedWYnkGiJ3ZADqwjhxj6jfVi5kvgczXp0=,tag:yrEBnwzthTjJP71zNzCubA==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd0NFa1FadzUwWjVLb3hu
            aWFsYTFiVjlUZzh4S2hTSG50ZkNDUjRjbUJRCi9qMVBKZElXZEVjcFYxVzY5aUxk
            czJ1YmRZT0xoaVYyaUErV1N2cFJDREEKLS0tIEtNM3pNMkw5TTdoSHBGQ1diM2d3
            KzREaHdaR2o4R1BCbng4eFlwOEtDNDAK4f+pcHfAwihReZTR5DOsFpKfhd0Efjfb
            vojt6wDbs9WtgHus1Ypb+LtZY3ICANaZubiuOqKYRzoUM4BGhvIBfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T10:21:52Z"
    mac: ENC[AES256_GCM,data:HVGrugN+g3TAk/2kfl9yROodbop5MEk77qtQ+brFjhdmw4iWxxuSNp5HHkkfnWB3UJ9ennBwUup5GQhysO6YqbJB01k94eDjUI9BzFOI7Ses2bOHYnEm5/RP8dJYcfTcCXxT9nad8t5rfEN+KOYPFLBURE67HJF310zN13Fa2MQ=,iv:zlEDjSqt1SpBGT1IWz1Tuk2rn17B7AJHhumFwbXOP7Y=,tag:URI/lIKx4g8e0tuSKjQ9pA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
