apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:pwvr3F/TvQjknbercFeh3rEjV5XkiGXQtYXfsnRqUiTZ86+VA9+Fn39KnsnmyjEBnV6sjSILpoKfrCMGDM3iyCm7YIzmddwRULPQ+pTJwoR25E/tuOQKiHucOORvrj9TdClGVYBPkLTb,iv:mfbYYEmgJ+YyHW+XXQbQBYzhJnLsGblYYh3Do4PXCqs=,tag:o9fVtWOYmxskX7dWugB5FQ==,type:str]
sops:
    age:
        - recipient: age1csm4q7qm27z74t9e42ha30pvujcm3a3gzhnvmpr04wwwsqjxp9jqhsnreg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZXNUdHJPcko2bWxIOURr
            RE5MaTBCRzZKYVFzakkxR0JMRmJkanBMMkJjClNoVklMMmFPek9CMGJEVXlBY2hY
            YkhqTzNxbVR2WWRFZkk0T3k4amJ4Z00KLS0tIHlpWUxydllDVmVnWVdFbGlVa1ZW
            bVNmQUV4djR3ditUamtZOWlieEoyZnMKkKpfW/FLjzZuYit3HYxlNft/+ZHt8ofq
            dlxz9ZJ9Z2MQNSbFvdFBsT74cNp4KFmoExT2yZb6HRgO7ue1oGikYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-16T04:38:45Z"
    mac: ENC[AES256_GCM,data:mt4qiL7CLcImfZ6jH7gKPx1Z/p3X9Jmsh6JTwPA8YsIK0vvvFqgEy/KVbGWIEo9tyQW+rw9iltsPMECxmXeOowg1qtBvPL2ofZQwYy/csHFFHZdD/rBl034/AcF4GfrZYDxzCBjX06HRTN7ATGRLqo3jHsF62SQrD6Jy2djBZSI=,iv:rw0R5KwphtMObXAgdVvnaUaP+kyWQrMv7cOs61HLt64=,tag:FF6S1kmz3yAC0B/XoODNNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
