apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WOkUaGPzCducvA2nSRj3fW/vPB7ODy+dp1M1r8h0hiu70DOzyVVydkA6HzJGcCPf6In2SQ9YUoLIyWruIphFJcbEs+sQPU94Wj8SzvzNfho+YHrGBIRPpsIcDvD6P8viEHrjp69/RGnV,iv:eLfZBhlPtnf1nY0yxtiU51iOXMhRgJfjHYJtw3cK7Ng=,tag:GssJwFMBpCjrU1kLX5mJ0w==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa0oxMjFveHNOai9DTWxp
            ajRVZFI1V0dSMG0zVHIrYjBXRjhjdHVIVFVRCnRtOEtCNmtvVkhtVXhUSGJJWUZm
            YWpZWHkwbGR5NjA2VklBSXFTVXRnUTAKLS0tIHhMb3BESUlzc1RYMzNrMXNaMUdi
            MWdibVZzZE9qQTRhekw5c2JGR25CY1UKJ8oVM6bhe8MT5/ENSgAYaUG9e50Y9esO
            0sgSgnZm30v6v2cvHR7GB5AhnS2HggF1iVRkcPIeU+YlAcRGig7row==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:04:25Z"
    mac: ENC[AES256_GCM,data:+JJME7ToUyhFfwaZ7N3vDhl2QecDL8MOOPcEjSUCUFJHiQWVYvArO5BcQAOfcczTJqydUM2MDCpzRUABZMwZS9GF2KpV2cS1QhNmxJ2mObGf4eZHNhRsVtOn/3q8FzdFyveu/LPE3Pcu3XSFKmTVv53VDP9HmzjeEohEm6ov/NA=,iv:gQ3Z00xw7Pp7Lw/amQX90o+xpKhFlgCo6t9XQY73RYA=,tag:dLQQkZX88IWr+G+Hp23eFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
