apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:rAJOm8IRq9vz4zBbJ9Bb+v2/D7JNlpmF61DajogYjpvF6yg7Cdh8d+xO/X7l+sBg8Qvb2y9Mhnqqzq+rF3d3aTs5lcreBOkG0PChtHEMkrqmpnJrRVMTxMYfppV5/YUeZls6NLIiVI7+,iv:W9xztubRmyt/Ss2MC1RgSKBlMSduae7R4M8HbHFi8go=,tag:Xf2Ehqnu38eqqGyIvVUUpQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR2RuTXNmR28vUnIwNlIr
            Mi9EUmxzbGtkNDc2TFhOSUd0VkhrTmZPZFR3CnY0a242SGpFbXNaN1NxbU9WVzJy
            anhRNjk2TEFpN2hxclF2QkEzdHdmaXcKLS0tIHVyR2dZN0U3d0ZWQWo1WWcyTWlY
            Nk9PTTdJM1ovMjdqNDFpOGFZZWJ2dEUKEiCOWDND9dxhyRPcQvjOmzmucJsxMOGa
            AnZ4e9L/cpQptJ6Q2GVYU4GPM5+5brXZ+NqGLFQLL08VgJfxar1Tow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:G0NKfy9rFBnmOJVXFbcLMEETk6Daq4scZ+Nv/60Gul/QHpsi3XJUWgLAZykXV8nEwqObvQ+e6ygfyXm1Z4sNTmGa2SVujsHNGe3sLWqF358OonfGL5+qvi7VvqFiD/7wwj9HhqdrU1A0L5fplp6OQZ/y+D/4VeESqwuKUXIZlRE=,iv:T84pJjvC271QF02mVBg/aeV0vb/RQy5njw1ci9OhZ9o=,tag:+xhF43f7jQPZh2LAmgVCSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
