apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:QTaIZybRNJVjwvtD5LgihRWV1CN7jWVoWhpud5oEnGuEXxqO/lQVxJqjFUNxH0jivsKGx2mBmW0luuEzConOsWTjrqGwOfZiC9T22JD372Q61avvvobjAQuZSF3pV0cuePj2qHz1hNDq,iv:zAOtVz/RxvI6cyVuGBMNI8XylsD88sRMKeSVI9R8CBE=,tag:5OzHl8qx7U4b3V4y9/XmDQ==,type:str]
sops:
    age:
        - recipient: age1qn66rws9pydcwqwn5d49fc9z7uemdrlj73tk2sgu9vmq5efqj50sdn93ch
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVXpqM0o2V3Jya3M0a2ZK
            TWk5WVhqRlEycmo5WXNxNVdKdHpIS3QxdzI0CndPWEZsb1UrNDFwK0pWRTFuM0pv
            aVBqZ08vVUtHYnRBVzUxYmpFdnZjOFUKLS0tIEhjZThncFE4RW1aRDZSV2RoL2FW
            Q2trb2E1Zi9pbGRjNzc4NEYyUDJwT0EKlcVduqKcW3/i2kEQ2xnnX49Wj5W3WpMB
            wTmBMWmDvXnstStzYRyqpIJt6SaCMuBpEGuRtUxrZBSN7Qf/qlNijA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:51:31Z"
    mac: ENC[AES256_GCM,data:1W90egdr7KV4njfDIOChY1VwSX4qkh6ngVgB2UA9vV7Aygt5VBBCk2pd+bAksMPg8/5xrAbCGNSqe8Pqw/BtWZMvVZasfqf2b8ukr/GWTdwvECHZr3Q12zfFwEjYt50lVjtSYyCLuyCsmflVdykmxUSIxfAmDy8zsgcb8KMApZ4=,iv:UqazbaswVPipDf8SGl156yEjYkhPt9Vs+qGx1ci9buc=,tag:VLtnCSM6SaIuGbwC7ys7CA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
