apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:DdGPu7PAfuxmnXEGTiLbOID6f7BC7CAJKaatwt8HJHFkZBV/qFHQLhMw7ueRpAPV+OmorIPdaBqyZLe/ttDrcmUkqVoJ1jpWep4WMcStgMKgY8rmttV+sm8qSGLE211thvwQsxeRHpUk,iv:dWEXCw1nQGNDvMu5LyZ9o40UqqelkA7huT3YBLII4aw=,tag:dnZ0zEU9na1+1YqMWHYFcQ==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxM0w1RHNEQytrcUpsZWpO
            SzliR0JsNU0wanlxUDVvUmZSbCt2a0x6L2c4CnFFNHZMT1NmSVpPNW5FUGdDVHIy
            MzVyMVNnaXdwa0wyTTdIRFZQRVBVME0KLS0tIGhKVnRhWUpNN2hnKzIxdHdXWmhs
            Y0lZUVMyU3h4SklJSkRHcGwzS01CRHMKPSEAu8aRwTE9XzuoCMyICU6hvPWkLnUH
            kvDh3S0111+4phFTYXlClbH4umdvXIj1z228O/J7lnCVCYg9bd8cKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:16:27Z"
    mac: ENC[AES256_GCM,data:xL0F/jCCWnUX9f4oLSm2zMAPvnUTR2JCYbT02eN2aY0+t0YbuKzAuGtmXghX7cydta/HfSNRlCEtpqRczmWtKOX+TBOU7lePGmez8b8wfMrtqN7qIj4qmDB3La6yVOQobIPOhyGcEWm3QM6e3O0XvZUbPQcmANtGBzhaAd7xctQ=,iv:psJ03VTzuKbHcVmwY65zT2AM34PfUPofro2LgNooidw=,tag:MG1m0UnwQRrpUwR/oF0yBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
