apiVersion: v1
kind: Secret
metadata:
    name: thakurnishu-packages-read-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:aRa/ahDIhTmK1GlZ6ZLVjcT4JT/rcCSTVPwwLLEgzXTawofCrzpaGq8Liw23TRdrOYink/OmEO9mUMA36FdGeDD6+M5RJntQdW3W69QTqKaXRtRTk0tROOwEtTE7mpkvhgipBq9aF2Nn,iv:wqw5zuSyvllJVyzUrO9i5THrvQfY4hL5NvXOF5B9+ck=,tag:eowTlta5MiwtsWSZO6jK3A==,type:str]
sops:
    age:
        - recipient: age1ldxd7slv9n4qde9n67gljd43tr5s35a9e3l8ue806c9k2566s3vsgd7aka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOGZVS2VqUlQvS2ViOVVE
            VnNYcDIwdVlRY1o5dGdjdVdiN0hnOW1haGhjCnhlM3hHUzRXYVVldWdOd0VLK1Ix
            Z1JTZnNydmRoVmFEamdJRmhjQmVHd3cKLS0tIEFsaWh4NWdwUysrcjc2UlFKc1h3
            a2tMM1RUV1BheUVQNlduaDZpZmRqQ0kKtB4PsFUzJnrZUypX8Bi8zGIwnBfxxK30
            hXeIMEC0f2+Etkxmf1ZUBszd63RPPX3RULvOGZcaWfspdxx3mDFqHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-27T14:43:29Z"
    mac: ENC[AES256_GCM,data:j7aAJ84vE0LNFoVcOQi7N/8362kHKz8d1ixUYPeWo0xUjAdEQ6lGyq3jr52jXGABjCeItCfnxFnhD9tYNNoY5ynMGZu6Xr3yalPJ1213s3T6jY5N7bp0MAaLk8mPrjHpz1erTa1a2hUTdQUyI/YQi6GgC38OkovkX+lpnvSoob8=,iv:V9+HWRNN6PqFepD5P5wSMAuCjojAau0MbNwa+GMARG8=,tag:3BAOJ+f2x5xx3ScTi1qjDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
