apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
spec:
  interval: 30m
  releaseName: metallb
  timeout: 30m

  chart:
    spec:
      chart: metallb
      version: '0.15.*'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      interval: 5m

  values:
    prometheus:
      rbacPrometheus: false
      serviceAccount: "kube-prometheus-stack-prometheus"
      namespace: "monitoring"
      podMonitor:
        enabled: false
      serviceMonitor:
        enabled: true
        speaker:
          additionalLabels:
            release: kube-prometheus-stack
        controller:
          additionalLabels:
            release: kube-prometheus-stack
