apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m
  releaseName: external-dns

  chart:
    spec:
      chart: external-dns
      version: '1.19.0'
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns

  values:
    provider:
      name: pihole
    policy: upsert-only
    registry: noop
    sources:
      - service
      - ingress
      - gateway-httproute # enabled when gateway api crds are installed in cluster
    domainFilters:
      - nishantlabs.cloud
    envFrom:
      - secretRef:
        name: pihole-info
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    logLevel: debug
