apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: signoz-httproute
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames:
  - signoz.local.nishantlabs.cloud
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: signoz
      port: 8080
