# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: homelab-pg-cluster-backup
# spec:
#   immediate: true
#   schedule: "0 0 3 * * *"
#   backupOwnerReference: cluster
#   cluster:
#     name: homelab-pg-cluster-v0
