apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelab-pg-cluster-vault
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-kv-secrets
    kind: ClusterSecretStore
  target:
    name: homelab-pg-cluster-vault
    template:
      type: kubernetes.io/basic-auth
  data:
  - secretKey: password
    remoteRef:
      key: infra/database/postgres
      property: password

  - secretKey: username
    remoteRef:
      key: infra/database/postgres
      property: username
