apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kv-secrets
spec:
  provider:
    vault:
      path: "kv-secrets"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: external-secrets
