apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/external-secrets
  - vault-token.secret.sops.yaml

patches:
  - path: clustersecretstore.yaml

namespace: external-secrets
