apiVersion: v1
kind: Secret
metadata:
    name: vault-token
stringData:
    token: ENC[AES256_GCM,data:Trwl+1CpeChqoASGlWL5+pri9MUozrkQzLVUTg==,iv:D8Tk2YjGU9GOPsWAamDESSUZusRAxMto1L3qWTaYG+s=,tag:/QWPwNFy1QpW1UcZ8VxKqg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWEZlR1JtdkMwa0lLYVVu
            YkdsVWhMWDZjTFQvbzVXWnF3Nm5BOFFBWWtBCkF3SU9aeHVZQmNSVXRHa0V1ZDBp
            Y1l5REJSWmtBN3RzSmEyL3QrRlhzVFEKLS0tIEhieXRWcFJJeFhZWVdLelh3RHI1
            WXlHZlVFWlJUTFNDUFhTSGpTV0Q3dTQKLdHIrlHHZ0BpDDCpG/EqUbYpKG2cbYNy
            DfmQ+RAQxMZAjCjgyJdeAryukVxph8Q8ICcG6QiTW+4vBUO/DjheNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T07:16:27Z"
    mac: ENC[AES256_GCM,data:6LUsCIYlMe1dRQMKMr9jfGfii1CDVuJuwpJywLGgND2urQc6j+1rV2eYQh7VhcmQGyd1qNOhLLwunINVvR610BWbx0U45BhdLNtQD5RTTeCHMGWej1UBx4AvSwTddRbVoxzJBrW9VdMHhUvi8sh9G+spIGL3kx6hnfzPk0FRllY=,iv:DKBwpY2hxpxLH+rrxKHh1pTW1UkCJl9Inhz4cgK0v70=,tag:KlaNLdsnTow52mMG4tyBMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
