apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - ipaddresspool.yaml
  - l2advertisement.yaml

namespace: metallb-system

patches:
  - path: patch.yaml
