apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkstack
  template:
    metadata:
      labels:
        app: linkstack
    spec:
      containers:
      - name: linkstack
        ports:
        - name: http
          containerPort: 80
#        resources:
#          requests:
#            cpu: "10m"
#            memory: 16Mi
#          limits:
#            cpu: "10m"
#            memory: 16Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
