apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    credentials.json: ENC[AES256_GCM,data:4qsurKxXGyD2zX+QkdCNffU2KwKZcJRCBdfjS2Wuveyy+ilrrePYwzGz56E4f4W1gCNQLVb0mweg8aX0Xx6eXzbuAlrTLTt4bEs5CLaxROY0JTDmHhuLm3cBoZHy4Nbf+H08iJkdNmnaljDvAHGUJKkHroiGdPHf3RAzysbBNq20CGF/J6muFgG0XB5gBdpDaHh03WOZpfdIT/fE3QnK25IcljNz5VHHM0y6wbrXu4NTkDy36R9RnhCEyEe4uX7VYw==,iv:gckt4RQUbuISP2QZBP+6XyWZW3FYnBHvi8p6wkDAiNA=,tag:aBm19XC2b7+dM4JC+UCXbA==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaG1lMkdFeG4wbG8zRjEv
            Tkh6WkRML1VYWVQ0c3VoTVc4MjlUS2d2VEhJClBuSk5LemxqNjBTTytPSmxjK2hq
            UVFYenJ0MjFCU21ieUQwTGFLbGZqeDQKLS0tIDdNUGlreHhidi9VRUtBMDVNUlhN
            dGdjQjdWS1dpZHNVNEtFODJ1TlEvTjgK99pVkp2/8eCDJOhxKw/NTsLNCFKoqc4O
            wLM436Zt09brpmA4tNGte7+0InToqjj35U73GwXZDMLtmQL22VfkMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:pkd8yQvDaRLzE3oXwM6+577caJiKzD6ovkVvx4/+f6qWpJzSBTtbqPujVEgL/5FT10HM9qPW5s2q5M2nqXFMRnvzelbtJdWR7r2TZF+5f3M8Xf4tg02yFpoJBU4jpqK2hTp/mWZgY/pK6UsodVAmqUBLIuiW18HS8FeTJtiaaBM=,iv:+P2IJ7Zh/jQJOEnqBxbETHDgfBmO6lXnEGGKsXq/dyM=,tag:jyATP09NKXlN6DDls9EwEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
