apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
spec:
  interval: 5m
  timeout: 60m
  releaseName: signoz
  chart:
    spec:
      chart: signoz
      version: '0.86.0'
      sourceRef:
        kind: HelmRepository
        name: signoz
