{
 "title": "Infrastructure / Metallb",
 "description": "Metallb key metrics",
 "tags": [
  "metallb ",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "layer2instance",
    "label": "Layer 2 instance",
    "query": "label_values(metallb_layer2_gratuitous_sent,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Address utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "metallb_allocator_addresses_total"
    },
    {
     "expr": "metallb_allocator_addresses_in_use_total"
    }
   ]
  },
  {
   "title": "Stale config",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(metallb_k8s_client_config_stale_bool)",
     "legendFormat": "client_config_stale"
    }
   ]
  },
  {
   "title": "Layer 2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(metallb_layer2_gratuitous_sent{instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "gratuitous_sent instance={{instance}} ip={{ip}} "
    },
    {
     "expr": "rate(metallb_layer2_requests_received{instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "requests_received instance={{instance}} ip={{ip}} "
    },
    {
     "expr": "rate(metallb_layer2_responses_sent{instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "responses_sent instance={{instance}} ip={{ip}} "
    }
   ]
  },
  {
   "title": "Client updates",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_update_errors_total[5m])"
    },
    {
     "expr": "rate(metallb_k8s_client_updates_total[5m])"
    }
   ]
  }
 ]
}