apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  interval: 30m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: '3.4.*'
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 5m
