apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:sB7WfzroqO8ONbniojwMy2C8ta3jtGPKuRNiWwgy0crXmnMNlpm3Xw==,iv:UozJ/E5kEUScieFpezwcByRairj6hgU8Pwn+koEsEhk=,tag:v+EI45NfjthcxYx1RBTtfA==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VXJrcGFrdDIrL3FXRDRC
            WndmVlcwUy82ZDZ0RE1lT292TWN2MnpXcmk4CmVxdmZXVHEwd0R3a0tuNEV2WmFi
            L05SUm0xYmRVSU8wUGxKdEpZblF0K2cKLS0tIGdUeU1DdEIwekR3SDBsK3BwTjFT
            bERKT3c2dlpDNCtrcWJ3RnFIclRyL1UK+4IYZpdj5/tltd+SsERaIUgjUY7iTrNs
            WF5h8d7bd+MyFWYbou+DT299PJoW+E2FYdUQuYq5qRW+tpdUh6te7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:PtUx/IHdziiP1N8i2tibQVJkHF/xpJvZMNpUUYyUHliXGj+AM4vceNOJ2rr4lGH6frnoK7y9kT2L2bh4e0jP5TRnq+/Tkz1QBBVcKXHDMSI2cITmonGLoJBjA0qMbTf5lGoOlobPq6XZz7xDADSdYFD0stYDviPSZaFlpcwCiCE=,iv:OaCMcKVDYpd+bbD0k7pSz4cH2faP7tSI1nHbhP3BnMA=,tag:A9VKOCIcvklGOwY0/O2vAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
