apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mlflow
spec:
  interval: 5m
  timeout: 60m
  releaseName: mlflow
  chart:
    spec:
      chart: mlflow
      version: '1.8.1'
      sourceRef:
        kind: HelmRepository
        name: mlflow-community-chart
