apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/monitoring

patches:
  - path: grafana-httproute.yaml
  - path: prometheus-httproute.yaml

namespace: monitoring
