apiVersion: v1
kind: Secret
metadata:
    name: vault-token
stringData:
    token: ENC[AES256_GCM,data:vRA/rixt8wdN294vHVcFSwkscqACFndsFwLCLw==,iv:kd4/jdI6DmviL6GYoxK7qklAcQEb55C9CbWNthBCl9g=,tag:2aOENnUkcTSMIPC/+sdpLg==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByakFNU3ZKVzVGcjRmNDM1
            aDBMS2hvRjk5OE1VRmluUjJkaUZUdzY3WlRNCndULzVBTUJqYWxMVWk5bllSM2Fx
            dWt1QW1ObU5tWmpSMXhHaFE3R05WZWcKLS0tIGxsb3UyVmZQSlQvT0JnaCs5Q2J0
            cXRKWG9LalNxWjFzQnpGMCtSWGhOWFkK2L/4sY/YnwKN2AK2An6o5DEh6Xzga6IB
            FE5giMToZtfgEjAR7wMp/aIST+9Q1lycZcMt5+BU4UouZoAZlRsdVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:04:25Z"
    mac: ENC[AES256_GCM,data:SsbINnEIaKItKd2aJ/3obvdXXNwqSaHhGSdGBuW26476UJBuWUfuHQGWC33swWBPwsMyarCyYkjLGjdCtx2Vxxd/fW5FH9GzhqgQA9xSqMaguUvZ59K8trwhEhMTAeXOww9pmHE9O9f1fxzUaq6laTOENH7wvU9ChV9gSh9tueo=,iv:R4FygnnbCm1rovNQettuik5Y6/5TlLCO/2XR9E1WTrY=,tag:VpUrlXL5IV0mPymYhqE7Aw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
