apiVersion: v1
kind: Secret
metadata:
    name: vault-token
stringData:
    token: ENC[AES256_GCM,data:Xv/KmzBsZrbwEsdNsCYFX3VSOuPw82ZTNYjPhA==,iv:tsxdeGlbFYd+0mtLwx/lwdr/K69jeicsJbML1gurnrQ=,tag:seTngSliOpBKlYT28fi5Ng==,type:str]
sops:
    age:
        - recipient: age1qx7eft90dsjujszrzswmkhxc6npk3n7t47juul03ah0nj6fnjg7sj6ryr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTlpBb29JZFUzNjJFTWs1
            OHJSWXdnSCtyWSs4Q1JQUXJtb3VhdGZlRGtVCnFlTUtvS1E1c0p1anlldWpOYlZu
            ZjY3ajkvVWl5SFBCSDUyV0crQndnWWMKLS0tIGdLV3Z2b25CVTBUeDBpeDhKV2w5
            NkIvSU1Ta29paGNCUjR4YVF5ODhoQ1kKXckNEkb54G9B/+gRVIIaNcxOYUCz20EW
            8oIYDKWBuFw1+56M2zanbwsWpxDcwXalt02H/FyuHeI5n6D+3hyXNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T15:25:08Z"
    mac: ENC[AES256_GCM,data:nbjiGLzY+SfjGX3IB1FY+K3Ac3mwdi2fwjvH43HQnf62CaUKP/iaJpHT2X7PZzquoof7RiDDJ65+wBHiASCst1MywmQsnZB/Lq3g9xLihx3Pm2mLWgd8BCN3CIgmfZZiDQVr4MQit5D+o453NsmM8PWKwPDEbixzmYRN2rWkrLY=,iv:5hYkyhJ8S+6vzaVxLNwh7M4VGVlMszsWEaHWHAz0zSI=,tag:INMx+YGvECI18TcAywTmVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
