apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/metallb

  - ./external-secrets
  - ./cloudnativepg
  - ../../base/cert-manager
  - ../../base/nginx-fabric-gateway
