apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - repositry.yaml
  - release.yaml
  - namespace.yaml


configMapGenerator:
  - name: traefik-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
