apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 5m
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: '1.28.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 5m
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: '1.28.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 5m
  releaseName: istio-cni
  chart:
    spec:
      chart: cni
      version: '1.28.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
spec:
  interval: 5m
  releaseName: ztunnel
  chart:
    spec:
      chart: ztunnel
      version: '1.28.1'
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
