apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/n8n
  - ../../../base/secrets/database-backup-to-gcs.secret.sops.yaml
  - namespace.yaml
#  - pg-cluster.yaml
#  - pg-cluster-backup.yaml

namespace: n8n

patches:
  - path: release.yaml
