apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
spec:
  interval: 30m
  releaseName: pihole
  timeout: 30m

  chart:
    spec:
      chart: pihole
      version: '2.34.*'
      sourceRef:
        kind: HelmRepository
        name: pihole
        namespace: pihole
      interval: 5m

  values:
    replicaCount: 1
    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: "192.168.1.245"
    admin:
      enabled: true
      existingSecret: "pihole-admin-password"
      passwordKey: "password"
    persistentVolumeClaim:
      enabled: true
      size: "128Mi"
      storageClass: "longhorn"
