apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-scale-set-controller
spec:
  interval: 5m
  releaseName: arc-runners
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: '0.12.1'
      sourceRef:
        kind: HelmRepository
        name: oci-arc-charts
        namespace: arc-runners

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-scale-set
spec:
  interval: 5m
  releaseName: arc-runner

  chart:
    spec:
      chart: gha-runner-scale-set
      version: '0.12.1'
      sourceRef:
        kind: HelmRepository
        name: oci-arc-charts
        namespace: arc-runners

  values:
    githubConfigUrl: "https://github.com/thakurnishu"
    githubConfigSecret: arc-github-app-secrets
    maxRunners: 3
    minRunners: 0
    #runnerScaleSetName: "ubuntu-homelab"
    containerMode:
      type: "dind"
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.325.0
