apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runner-scale-set-controller
spec:
  interval: 5m
  releaseName: arc-runners
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: '0.12.1'
      sourceRef:
        kind: HelmRepository
        name: oci-arc-charts
        namespace: arc-runners
