apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/owasp-dependency-track
  - namespace.yaml
  - httproute.yaml

namespace: dependency-track

patches:
  - path: release.yaml
