apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dependency-track
spec:
  chart:
    spec:
      sourceRef:
        namespace: dependency-track
  values:
    apiServer:
      resources:
        requests:
          cpu: "2"
          memory: 5Gi
        limits:
          cpu: "4"
          memory: 5Gi
    frontend:
      resources:
        requests:
          cpu: "150m"
          memory: 64Mi
        limits:
          cpu: "500m"
          memory: 128Gi
