apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/sonarqube
  - namespace.yaml
  - pg-cluster.yaml
  - ./secrets

namespace: sonarqube

patches:
  - path: release.yaml
