apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../../base/sonarqube
  - monitoring-passcode.secret.sops.yaml
  - sonarqube-password.secret.sops.yaml

namespace: sonarqube

patches:
  - path: release.yaml
