apiVersion: v1
kind: Secret
metadata:
    name: monitoring-passcode
type: Opaque
stringData:
    passcode: ENC[AES256_GCM,data:eWITpvchWd7EVjZUe/rOzxNh,iv:7Z6PZ+2Ia4hI2b2yBQkfFlbFV51UXeGp4/aVCpTyE1g=,tag:ezjfppXRnELp2ny8gSZuAQ==,type:str]
sops:
    age:
        - recipient: age1csm4q7qm27z74t9e42ha30pvujcm3a3gzhnvmpr04wwwsqjxp9jqhsnreg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzN2VNTzczOVJtdFM5Z1pF
            STVyRk1xNVJKekFscUFueDExUXFUNlNXajBNCitzVlhQU2pkM1VHU3RYaHF2aVo2
            cm5IRUFPWm1aMzVISi9Zbm5XdmFiQVkKLS0tIE84NnhUYUVYMGF1WjYvWnk4a0l1
            T3VOM3pjaW8zSTRkY1RLVktoekJXQkUKnWui5yszm1WmnBxiPW5OWQzsLV9498ig
            2DMAQVUO1J4zNXm+lwUt2SkC2QTvxN2A7FjRLRF76GAhVLOYltr/cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T11:18:44Z"
    mac: ENC[AES256_GCM,data:G36PwWulSmuONd/lixT5/BSA4nr6LmuygS/ijkDaW/Nqy5f0hzz2WWAPOE38pYcV+lQZn7JzMLLlX+eyn1NIc3KJl/5zUlmUf2I+ESQbyoVx6gsA8+cAWz6k8yC/HVcfx8Nwt8oPhO0PFIZAZPCBUe9ebH3IWpG5cTTwD+G5eVs=,iv:A1C4BdLp0aGsOf8BbkQg843DaIDAJJjC3IzuhXW0858=,tag:ohUHr7WlnnXgg/FJlTWHbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
