apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sonarqube-pg-cluster
spec:
  instances: 1
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  storage:
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: "gs://homelab-database-backup-nishantlabs/sonarqube"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d
