apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: sonarqube-backup
spec:
  immediate: true
  schedule: "0 0 3 * * *"
  backupOwnerReference: cluster
  cluster:
    name: sonarqube-pg-cluster-v0
