apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  chart:
    spec:
      sourceRef:
        namespace: sonarqube
  values:
    httproute:
      enabled: true
      gateway: traefik-gateway
      gatewayNamespace: traefik
      hostnames:
      - sonarqube.nishantlabs.cloud
    monitoringPasscodeSecretName: monitoring-passcode
    monitoringPasscodeSecretKey: passcode
    edition: developer
    setAdminPassword:
      passwordSecretName: sonarqube-password
