apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarqube
spec:
  chart:
    spec:
      sourceRef:
        namespace: sonarqube
  values:
    # InitContainer for database
    initContainers:
      extraInitContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z sonarqube-pg-cluster-v0-rw 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done']

    httproute:
      enabled: true
      gateway: traefik-gateway
      gatewayNamespace: traefik
      hostnames:
      - sonarqube.local.nishantlabs.cloud
    monitoringPasscodeSecretName: monitoring-passcode
    monitoringPasscodeSecretKey: passcode
    community:
      enabled: true
      buildNumber: "25.6.0.109173"
    setAdminPassword:
      passwordSecretName: sonarqube-password

    # Database Setting
    postgresql:
      enabled: false
    jdbcOverwrite:
      enabled: true
      jdbcUrl: "jdbc:postgresql://sonarqube-pg-cluster-v0-rw.sonarqube.svc.cluster.local:5432/app"
      jdbcUsername: app
      jdbcSecretName: sonarqube-pg-cluster-v0-app
      jdbcSecretPasswordKey: password

